import type { MotionStage, Point, Pose } from "./motion-model";

export type ProArchetypeId =
  | "alcaraz_forehand"
  | "federer_forehand"
  | "alcaraz_modern"
  | "djokovic_compact"
  | "federer_classic"
  | "sampras_serve"
  | "kick_serve"
  | "edberg_volley";

export type StageTelemetry = {
  joint: string;
  athleteValue: string;
  proValue: string;
  deltaLabel: string;
  deltaColor: string;
  coachingCue: string;
  efficiencyLoss: string;
};

export type ProArchetype = {
  id: ProArchetypeId;
  name: string;
  signature: string;
  applicableActions: string[];
  stanceType: "Open / Semi-Open" | "Neutral / Closed" | "Universal Platform";
  kineticStrength: string;
  racketDropLag: string;
  shoulderCoilDegrees: number;
  contactSpacingMm: number;
  badge: string;
  themeColor: string;
  stagePoses: Record<MotionStage, Pose>;
  keyDeltas: Record<MotionStage, { joint: string; targetMetric: string; coachInsight: string }>;
  telemetryByStage: Record<MotionStage, StageTelemetry>;
};

function pt(x: number, y: number): Point {
  return { x: Math.max(0.04, Math.min(0.96, x)), y: Math.max(0.035, Math.min(0.96, y)) };
}

export const PRO_ARCHETYPES: Record<ProArchetypeId, ProArchetype> = {
  alcaraz_forehand: {
    id: "alcaraz_forehand",
    name: "Modern Heavy Topspin",
    signature: "Semi-Western Whippy Topspin",
    applicableActions: ["forehand"],
    stanceType: "Open / Semi-Open",
    kineticStrength: "Explosive Hip Rotation ➔ Lag Whip",
    racketDropLag: "Deep below ball line (+18cm lag)",
    shoulderCoilDegrees: 108,
    contactSpacingMm: 540,
    badge: "Tour Benchmark · Dynamic Whip",
    themeColor: "#f97316",
    stagePoses: {
      ready: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.42, 0.22),
        right_shoulder: pt(0.58, 0.22),
        left_elbow: pt(0.40, 0.35),
        right_elbow: pt(0.60, 0.35),
        left_wrist: pt(0.48, 0.44),
        right_wrist: pt(0.52, 0.48),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.50),
        left_knee: pt(0.42, 0.72),
        right_knee: pt(0.58, 0.72),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
      unit_turn: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.58, 0.23),
        left_elbow: pt(0.38, 0.32),
        right_elbow: pt(0.68, 0.36),
        left_wrist: pt(0.32, 0.34),
        right_wrist: pt(0.70, 0.42),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.51),
        left_knee: pt(0.43, 0.73),
        right_knee: pt(0.59, 0.74),
        left_ankle: pt(0.40, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
      backswing: {
        head: pt(0.50, 0.13),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.59, 0.23),
        left_elbow: pt(0.40, 0.36),
        right_elbow: pt(0.70, 0.44),
        left_wrist: pt(0.40, 0.38),
        right_wrist: pt(0.72, 0.56),
        left_hip: pt(0.45, 0.51),
        right_hip: pt(0.55, 0.52),
        left_knee: pt(0.42, 0.74),
        right_knee: pt(0.60, 0.76),
        left_ankle: pt(0.39, 0.92),
        right_ankle: pt(0.64, 0.92),
      },
      forward_swing_contact: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.42, 0.22),
        right_shoulder: pt(0.56, 0.22),
        left_elbow: pt(0.44, 0.34),
        right_elbow: pt(0.38, 0.35),
        left_wrist: pt(0.42, 0.36),
        right_wrist: pt(0.24, 0.32),
        left_hip: pt(0.44, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.42, 0.71),
        right_knee: pt(0.56, 0.71),
        left_ankle: pt(0.39, 0.92),
        right_ankle: pt(0.59, 0.92),
      },
      follow_through: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.56, 0.22),
        left_elbow: pt(0.40, 0.32),
        right_elbow: pt(0.44, 0.24),
        left_wrist: pt(0.36, 0.28),
        right_wrist: pt(0.32, 0.20),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.44, 0.71),
        right_knee: pt(0.56, 0.71),
        left_ankle: pt(0.41, 0.92),
        right_ankle: pt(0.59, 0.92),
      },
      recovery: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.42, 0.22),
        right_shoulder: pt(0.58, 0.22),
        left_elbow: pt(0.40, 0.35),
        right_elbow: pt(0.60, 0.35),
        left_wrist: pt(0.48, 0.44),
        right_wrist: pt(0.52, 0.48),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.50),
        left_knee: pt(0.42, 0.72),
        right_knee: pt(0.58, 0.72),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
    },
    keyDeltas: {
      ready: { joint: "Semi-Open Platform", targetMetric: "1.25x shoulder width", coachInsight: "Balanced athletic base allows explosive hip coil." },
      unit_turn: { joint: "Non-Dominant Arm Tracking", targetMetric: "Left hand points forward", coachInsight: "Left arm reaches forward to measure ball distance and stabilize shoulders." },
      backswing: { joint: "Power Slot Lag", targetMetric: "18cm below ball line", coachInsight: "Let wrist relax completely into the slot for explosive upward whip." },
      forward_swing_contact: { joint: "Forward Reach Spacing", targetMetric: "54cm in front of lead hip", coachInsight: "Meet ball well out in front with high leverage and stable head." },
      follow_through: { joint: "Windshield Wiper Finish", targetMetric: "Wrap across left bicep", coachInsight: "Wipe up and over the ball to maximize topspin RPM." },
      recovery: { joint: "Dynamic Crossover Reset", targetMetric: "Instant split-step", coachInsight: "Push off outside foot back to baseline center." },
    },
    telemetryByStage: {
      ready: {
        joint: "Semi-Open Platform",
        athleteValue: "1.02x shoulder width",
        proValue: "1.25x shoulder width",
        deltaLabel: "Δ +0.23x Semi-Open Base",
        deltaColor: "text-amber-400",
        coachingCue: "Widen into semi-open stance for rapid ground reaction loading.",
        efficiencyLoss: "-8% hip uncoil speed",
      },
      unit_turn: {
        joint: "Non-Dominant Arm Tracking",
        athleteValue: "Dropped left arm",
        proValue: "Left hand points forward",
        deltaLabel: "Δ High Left Arm Tracking",
        deltaColor: "text-sky-400",
        coachingCue: "Extend left arm across torso to track incoming ball and lock shoulders.",
        efficiencyLoss: "-12% shoulder coil stability",
      },
      backswing: {
        joint: "Power Slot Lag",
        athleteValue: "5cm below contact",
        proValue: "18cm below ball line",
        deltaLabel: "Δ +13cm Deep Wrist Lag",
        deltaColor: "text-rose-400",
        coachingCue: "Drop the racket head deeply below ball line for violent topspin whip.",
        efficiencyLoss: "-21% topspin RPM generation",
      },
      forward_swing_contact: {
        joint: "Forward Reach Spacing",
        athleteValue: "34cm from lead hip",
        proValue: "54cm in front of hip",
        deltaLabel: "Δ +20cm Forward Lever Reach",
        deltaColor: "text-rose-400",
        coachingCue: "“Meet it out in front; whip through the contact zone.”",
        efficiencyLoss: "-18% linear kinetic transfer",
      },
      follow_through: {
        joint: "Windshield Wiper Finish",
        athleteValue: "Linear push follow-through",
        proValue: "Wrap across left bicep",
        deltaLabel: "Δ Windshield Wiper Finish",
        deltaColor: "text-emerald-400",
        coachingCue: "Wipe up and across the left bicep to maximize topspin RPM.",
        efficiencyLoss: "-15% spin RPM & heavy ball dip",
      },
      recovery: {
        joint: "Dynamic Crossover Reset",
        athleteValue: "1.42s baseline reset",
        proValue: "0.95s explosive crossover",
        deltaLabel: "Δ 0.47s Faster Recovery",
        deltaColor: "text-sky-400",
        coachingCue: "Explosive outside foot push-off back to baseline center.",
        efficiencyLoss: "-10% recovery readiness",
      },
    },
  },

  federer_forehand: {
    id: "federer_forehand",
    name: "Classical Liquid Lever",
    signature: "Straight-Arm Long Zone Forehand",
    applicableActions: ["forehand"],
    stanceType: "Neutral / Closed",
    kineticStrength: "Straight-Arm Extension ➔ Effortless Flow",
    racketDropLag: "Continuous fluid loop",
    shoulderCoilDegrees: 102,
    contactSpacingMm: 560,
    badge: "Tour Benchmark · Extended Lever",
    themeColor: "#818cf8",
    stagePoses: {
      ready: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.42, 0.22),
        right_shoulder: pt(0.58, 0.22),
        left_elbow: pt(0.40, 0.35),
        right_elbow: pt(0.60, 0.35),
        left_wrist: pt(0.48, 0.44),
        right_wrist: pt(0.52, 0.48),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.50),
        left_knee: pt(0.42, 0.72),
        right_knee: pt(0.58, 0.72),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
      unit_turn: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.58, 0.23),
        left_elbow: pt(0.37, 0.32),
        right_elbow: pt(0.68, 0.35),
        left_wrist: pt(0.30, 0.34),
        right_wrist: pt(0.70, 0.40),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.51),
        left_knee: pt(0.43, 0.73),
        right_knee: pt(0.59, 0.74),
        left_ankle: pt(0.40, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
      backswing: {
        head: pt(0.50, 0.13),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.59, 0.23),
        left_elbow: pt(0.40, 0.36),
        right_elbow: pt(0.70, 0.42),
        left_wrist: pt(0.40, 0.38),
        right_wrist: pt(0.72, 0.54),
        left_hip: pt(0.45, 0.51),
        right_hip: pt(0.55, 0.52),
        left_knee: pt(0.42, 0.74),
        right_knee: pt(0.60, 0.76),
        left_ankle: pt(0.39, 0.92),
        right_ankle: pt(0.64, 0.92),
      },
      forward_swing_contact: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.42, 0.22),
        right_shoulder: pt(0.56, 0.22),
        left_elbow: pt(0.44, 0.34),
        right_elbow: pt(0.36, 0.34),
        left_wrist: pt(0.42, 0.36),
        right_wrist: pt(0.22, 0.30),
        left_hip: pt(0.44, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.42, 0.71),
        right_knee: pt(0.56, 0.71),
        left_ankle: pt(0.39, 0.92),
        right_ankle: pt(0.59, 0.92),
      },
      follow_through: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.56, 0.22),
        left_elbow: pt(0.40, 0.32),
        right_elbow: pt(0.42, 0.22),
        left_wrist: pt(0.36, 0.28),
        right_wrist: pt(0.30, 0.18),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.44, 0.71),
        right_knee: pt(0.56, 0.71),
        left_ankle: pt(0.41, 0.92),
        right_ankle: pt(0.59, 0.92),
      },
      recovery: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.42, 0.22),
        right_shoulder: pt(0.58, 0.22),
        left_elbow: pt(0.40, 0.35),
        right_elbow: pt(0.60, 0.35),
        left_wrist: pt(0.48, 0.44),
        right_wrist: pt(0.52, 0.48),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.50),
        left_knee: pt(0.42, 0.72),
        right_knee: pt(0.58, 0.72),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
    },
    keyDeltas: {
      ready: { joint: "Posture Alignment", targetMetric: "Spine vertical 88°", coachInsight: "Tall, balanced platform with relaxed shoulder carriage." },
      unit_turn: { joint: "Shoulder Turn", targetMetric: "102° rotation", coachInsight: "Turn upper back fully before hand drops." },
      backswing: { joint: "Straight Arm Slot", targetMetric: "Spacious takeback arc", coachInsight: "Preserve spacious radius from chest for maximum leverage." },
      forward_swing_contact: { joint: "Extended Contact Reach", targetMetric: "56cm in front of lead hip", coachInsight: "Straight-arm extension through the forward contact corridor." },
      follow_through: { joint: "High Finish", targetMetric: "Above left shoulder wrap", coachInsight: "Extend out through target before wrapping effortlessly." },
      recovery: { joint: "Footwork Glide", targetMetric: "Balanced recovery step", coachInsight: "Glide seamlessly back into ready platform." },
    },
    telemetryByStage: {
      ready: {
        joint: "Spine Alignment",
        athleteValue: "76° spine tilt",
        proValue: "88° upright posture",
        deltaLabel: "Δ Relaxed Upright Posture",
        deltaColor: "text-sky-400",
        coachingCue: "Maintain tall, relaxed posture for natural rotational flow.",
        efficiencyLoss: "-5% swing rhythm",
      },
      unit_turn: {
        joint: "Shoulder Turn",
        athleteValue: "80° coil",
        proValue: "102° fluid coil",
        deltaLabel: "Δ +22° Fluid Upper Torso Turn",
        deltaColor: "text-amber-400",
        coachingCue: "Turn the upper back fully before initiating the arm takeback.",
        efficiencyLoss: "-11% effortless power",
      },
      backswing: {
        joint: "Straight-Arm Takeback Radius",
        athleteValue: "Cramped elbow radius",
        proValue: "560mm spacious arc",
        deltaLabel: "Δ +140mm Spacious Arm Radius",
        deltaColor: "text-rose-400",
        coachingCue: "Preserve a spacious straight-arm arc away from chest for maximum leverage.",
        efficiencyLoss: "-16% leverage efficiency",
      },
      forward_swing_contact: {
        joint: "Extended Contact Reach",
        athleteValue: "34cm from lead hip",
        proValue: "56cm in front of hip",
        deltaLabel: "Δ +22cm Straight-Arm Extension",
        deltaColor: "text-rose-400",
        coachingCue: "“Straight-arm reach through the ball; long hitting zone.”",
        efficiencyLoss: "-19% sweetspot ball exit speed",
      },
      follow_through: {
        joint: "High Classical Extension",
        athleteValue: "Truncated wrap",
        proValue: "High target release",
        deltaLabel: "Δ High Target Extension",
        deltaColor: "text-emerald-400",
        coachingCue: "Extend the arm completely through the target before releasing overhead.",
        efficiencyLoss: "-8% penetrating ball depth",
      },
      recovery: {
        joint: "Footwork Glide Reset",
        athleteValue: "1.38s baseline reset",
        proValue: "0.94s seamless glide",
        deltaLabel: "Δ 0.44s Footwork Glide",
        deltaColor: "text-sky-400",
        coachingCue: "Glide seamlessly into the center ready platform without hard emergency strides.",
        efficiencyLoss: "-9% court positioning",
      },
    },
  },

  alcaraz_modern: {
    id: "alcaraz_modern",
    name: "Modern Whippy 2HB",
    signature: "Two-Handed Dynamic Topspin",
    applicableActions: ["two_handed_backhand"],
    stanceType: "Open / Semi-Open",
    kineticStrength: "Explosive Leg Drive ➔ Whip Lag",
    racketDropLag: "Deep below ball line (+14cm lag)",
    shoulderCoilDegrees: 104,
    contactSpacingMm: 520,
    badge: "Tour Benchmark · Explosive 2HB",
    themeColor: "#06b6d4",
    stagePoses: {
      ready: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.42, 0.22),
        right_shoulder: pt(0.58, 0.22),
        left_elbow: pt(0.40, 0.35),
        right_elbow: pt(0.60, 0.35),
        left_wrist: pt(0.50, 0.42),
        right_wrist: pt(0.50, 0.47),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.50),
        left_knee: pt(0.42, 0.72),
        right_knee: pt(0.58, 0.72),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
      unit_turn: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.58, 0.23),
        left_elbow: pt(0.56, 0.34),
        right_elbow: pt(0.68, 0.37),
        left_wrist: pt(0.66, 0.38),
        right_wrist: pt(0.68, 0.44),
        left_hip: pt(0.47, 0.50),
        right_hip: pt(0.55, 0.51),
        left_knee: pt(0.44, 0.73),
        right_knee: pt(0.60, 0.75),
        left_ankle: pt(0.40, 0.92),
        right_ankle: pt(0.64, 0.92),
      },
      backswing: {
        head: pt(0.50, 0.13),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.59, 0.23),
        left_elbow: pt(0.58, 0.42),
        right_elbow: pt(0.70, 0.43),
        left_wrist: pt(0.68, 0.54),
        right_wrist: pt(0.68, 0.48),
        left_hip: pt(0.46, 0.51),
        right_hip: pt(0.56, 0.52),
        left_knee: pt(0.43, 0.75),
        right_knee: pt(0.62, 0.77),
        left_ankle: pt(0.39, 0.92),
        right_ankle: pt(0.66, 0.92),
      },
      forward_swing_contact: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.40, 0.22),
        right_shoulder: pt(0.56, 0.22),
        left_elbow: pt(0.32, 0.32),
        right_elbow: pt(0.44, 0.36),
        left_wrist: pt(0.26, 0.30),
        right_wrist: pt(0.30, 0.35),
        left_hip: pt(0.43, 0.50),
        right_hip: pt(0.53, 0.50),
        left_knee: pt(0.41, 0.71),
        right_knee: pt(0.57, 0.71),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.60, 0.92),
      },
      follow_through: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.45, 0.22),
        right_shoulder: pt(0.55, 0.22),
        left_elbow: pt(0.52, 0.28),
        right_elbow: pt(0.60, 0.26),
        left_wrist: pt(0.60, 0.18),
        right_wrist: pt(0.63, 0.22),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.44, 0.71),
        right_knee: pt(0.56, 0.71),
        left_ankle: pt(0.41, 0.92),
        right_ankle: pt(0.59, 0.92),
      },
      recovery: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.42, 0.22),
        right_shoulder: pt(0.58, 0.22),
        left_elbow: pt(0.40, 0.35),
        right_elbow: pt(0.60, 0.35),
        left_wrist: pt(0.50, 0.42),
        right_wrist: pt(0.50, 0.47),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.50),
        left_knee: pt(0.42, 0.72),
        right_knee: pt(0.58, 0.72),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
    },
    keyDeltas: {
      ready: { joint: "Base width", targetMetric: "1.28x shoulder width", coachInsight: "Wider ready base allows instant lateral push-off." },
      unit_turn: { joint: "Shoulder Coil", targetMetric: "104° rotation", coachInsight: "Turn upper torso fully past perpendicular with both hands set on grip." },
      backswing: { joint: "Racket Drop", targetMetric: "18cm below contact line", coachInsight: "Let non-dominant hand drive the deep slot drop." },
      forward_swing_contact: { joint: "Forward Spacing", targetMetric: "48cm in front of lead hip", coachInsight: "Meet the ball out in front with dual arm extension and head locked." },
      follow_through: { joint: "Elbow Elevation", targetMetric: "Both elbows wrapped high", coachInsight: "Complete the full wrap over opposite shoulder without decelerating early." },
      recovery: { joint: "First Step", targetMetric: "Dynamic crossover push", coachInsight: "Absorb landing and bounce directly toward center T." },
    },
    telemetryByStage: {
      ready: {
        joint: "Base Width",
        athleteValue: "0.98x shoulder width",
        proValue: "1.28x shoulder width",
        deltaLabel: "Δ +0.30x Wider Athletic Platform",
        deltaColor: "text-sky-400",
        coachingCue: "Widen your split-step base to load off ground instantly.",
        efficiencyLoss: "-6% first-step burst",
      },
      unit_turn: {
        joint: "Shoulder Rotation",
        athleteValue: "78° Upper Torso Coil",
        proValue: "104° Upper Torso Coil",
        deltaLabel: "Δ +26° Deeper Torso Coil",
        deltaColor: "text-amber-400",
        coachingCue: "Turn back until chin rests over leading front shoulder.",
        efficiencyLoss: "-14% elastic rotational torque",
      },
      backswing: {
        joint: "Racket Drop Slot",
        athleteValue: "6cm below contact",
        proValue: "18cm below contact",
        deltaLabel: "Δ +12cm Deeper Whip Drop",
        deltaColor: "text-rose-400",
        coachingCue: "Let the racket head drop below the ball line before uncoiling.",
        efficiencyLoss: "-18% topspin RPM generation",
      },
      forward_swing_contact: {
        joint: "Forward Contact Reach",
        athleteValue: "32cm from lead hip",
        proValue: "48cm in front of hip",
        deltaLabel: "Δ +16cm Spaced Reach in Front",
        deltaColor: "text-rose-400",
        coachingCue: "“Arms away. Meet it in front.” Full lever arm extension.",
        efficiencyLoss: "-14% linear racket speed leak",
      },
      follow_through: {
        joint: "Wrap Elevation",
        athleteValue: "Chest height finish",
        proValue: "High shoulder wrap finish",
        deltaLabel: "Δ Higher High-to-Low Deceleration",
        deltaColor: "text-emerald-400",
        coachingCue: "Wrap high past the ear without decelerating before contact.",
        efficiencyLoss: "-8% topspin RPM & depth",
      },
      recovery: {
        joint: "Re-Split Center",
        athleteValue: "1.42s baseline reset",
        proValue: "0.98s athletic push-step",
        deltaLabel: "Δ 0.44s Faster Net/Baseline Reset",
        deltaColor: "text-sky-400",
        coachingCue: "Push off the outside foot immediately after follow-through.",
        efficiencyLoss: "-9% next-shot positioning",
      },
    },
  },

  djokovic_compact: {
    id: "djokovic_compact",
    name: "Compact Precision 2HB",
    signature: "Two-Handed Linear Consistency",
    applicableActions: ["two_handed_backhand"],
    stanceType: "Open / Semi-Open",
    kineticStrength: "Ground Reaction ➔ Core Rotation",
    racketDropLag: "Ultra-compact slot drop",
    shoulderCoilDegrees: 100,
    contactSpacingMm: 480,
    badge: "Tour Benchmark · Precision 2HB",
    themeColor: "#10b981",
    stagePoses: {
      ready: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.42, 0.22),
        right_shoulder: pt(0.58, 0.22),
        left_elbow: pt(0.40, 0.35),
        right_elbow: pt(0.60, 0.35),
        left_wrist: pt(0.50, 0.42),
        right_wrist: pt(0.50, 0.47),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.50),
        left_knee: pt(0.42, 0.72),
        right_knee: pt(0.58, 0.72),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
      unit_turn: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.58, 0.23),
        left_elbow: pt(0.55, 0.34),
        right_elbow: pt(0.67, 0.37),
        left_wrist: pt(0.65, 0.38),
        right_wrist: pt(0.67, 0.44),
        left_hip: pt(0.47, 0.50),
        right_hip: pt(0.55, 0.51),
        left_knee: pt(0.44, 0.73),
        right_knee: pt(0.60, 0.75),
        left_ankle: pt(0.40, 0.92),
        right_ankle: pt(0.64, 0.92),
      },
      backswing: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.59, 0.23),
        left_elbow: pt(0.57, 0.41),
        right_elbow: pt(0.69, 0.42),
        left_wrist: pt(0.67, 0.53),
        right_wrist: pt(0.67, 0.47),
        left_hip: pt(0.46, 0.51),
        right_hip: pt(0.56, 0.52),
        left_knee: pt(0.43, 0.75),
        right_knee: pt(0.62, 0.77),
        left_ankle: pt(0.39, 0.92),
        right_ankle: pt(0.66, 0.92),
      },
      forward_swing_contact: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.40, 0.22),
        right_shoulder: pt(0.56, 0.22),
        left_elbow: pt(0.33, 0.32),
        right_elbow: pt(0.45, 0.36),
        left_wrist: pt(0.27, 0.30),
        right_wrist: pt(0.31, 0.35),
        left_hip: pt(0.43, 0.50),
        right_hip: pt(0.53, 0.50),
        left_knee: pt(0.41, 0.71),
        right_knee: pt(0.57, 0.71),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.60, 0.92),
      },
      follow_through: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.45, 0.22),
        right_shoulder: pt(0.54, 0.22),
        left_elbow: pt(0.53, 0.28),
        right_elbow: pt(0.61, 0.26),
        left_wrist: pt(0.60, 0.18),
        right_wrist: pt(0.63, 0.22),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.44, 0.71),
        right_knee: pt(0.56, 0.71),
        left_ankle: pt(0.41, 0.92),
        right_ankle: pt(0.59, 0.92),
      },
      recovery: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.42, 0.22),
        right_shoulder: pt(0.58, 0.22),
        left_elbow: pt(0.40, 0.35),
        right_elbow: pt(0.60, 0.35),
        left_wrist: pt(0.50, 0.42),
        right_wrist: pt(0.50, 0.47),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.50),
        left_knee: pt(0.42, 0.72),
        right_knee: pt(0.58, 0.72),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
    },
    keyDeltas: {
      ready: { joint: "Posture Alignment", targetMetric: "Spine vertical 88°", coachInsight: "Tall, balanced platform with zero tension in shoulders." },
      unit_turn: { joint: "Dual Hand Unit Turn", targetMetric: "Both hands lead coil", coachInsight: "Turn upper torso as one compact block." },
      backswing: { joint: "Compact Slot", targetMetric: "Efficient slot drop", coachInsight: "Keep racket path clean with zero wasted motion." },
      forward_swing_contact: { joint: "Head Fixation", targetMetric: "0.0° head sway at hit", coachInsight: "Keep chin glued over the shoulder until both arms extend through." },
      follow_through: { joint: "Shoulder Wrap", targetMetric: "High dual wrap finish", coachInsight: "Both hands wrap seamlessly around neck." },
      recovery: { joint: "Footwork Reset", targetMetric: "Balanced split glide", coachInsight: "Re-center seamlessly without emergency strides." },
    },
    telemetryByStage: {
      ready: {
        joint: "Spine Verticality",
        athleteValue: "76° forward lean",
        proValue: "88° spine alignment",
        deltaLabel: "Δ +12° Taller Spine Platform",
        deltaColor: "text-sky-400",
        coachingCue: "Keep upper torso tall with relaxed shoulders before coiling.",
        efficiencyLoss: "-5% balance consistency",
      },
      unit_turn: {
        joint: "Dual-Hand Unit Turn",
        athleteValue: "Arm takeaway drift",
        proValue: "100° upper torso unit",
        deltaLabel: "Δ Zero Extraneous Arm Takeaway",
        deltaColor: "text-amber-400",
        coachingCue: "Turn the shoulders as a rigid single unit with both hands locked on grip.",
        efficiencyLoss: "-10% timing reliability",
      },
      backswing: {
        joint: "Compact Slot Drop",
        athleteValue: "Excessive drop lag",
        proValue: "10cm compact slot",
        deltaLabel: "Δ Ultra-Compact Slot Drop",
        deltaColor: "text-sky-400",
        coachingCue: "Keep the backswing loop minimal and clean to handle fast incoming balls.",
        efficiencyLoss: "-12% direction repeatability",
      },
      forward_swing_contact: {
        joint: "Head Fixation at Impact",
        athleteValue: "7° head sway at hit",
        proValue: "0.0° head fixation",
        deltaLabel: "Δ Locked Head at Impact",
        deltaColor: "text-rose-400",
        coachingCue: "“Head locked at contact; let the core rotate.”",
        efficiencyLoss: "-15% sweetspot accuracy & depth",
      },
      follow_through: {
        joint: "Shoulder Wrap Finish",
        athleteValue: "Variable follow-through",
        proValue: "High seamless neck wrap",
        deltaLabel: "Δ Seamless Neck Wrap",
        deltaColor: "text-emerald-400",
        coachingCue: "Finish with both elbows wrapped around neck for repeatable ball arc.",
        efficiencyLoss: "-6% stroke repeatability",
      },
      recovery: {
        joint: "Balanced Split Glide",
        athleteValue: "1.42s baseline reset",
        proValue: "0.92s balanced glide",
        deltaLabel: "Δ 0.50s Smooth Lateral Recovery",
        deltaColor: "text-sky-400",
        coachingCue: "Glide sideways into ready stance without emergency balance adjustments.",
        efficiencyLoss: "-11% balance for next shot",
      },
    },
  },

  federer_classic: {
    id: "federer_classic",
    name: "Classical Flow 1HB",
    signature: "One-Handed Flow & Release",
    applicableActions: ["one_handed_backhand", "slice_backhand"],
    stanceType: "Neutral / Closed",
    kineticStrength: "Torso Coil ➔ Effortless Release",
    racketDropLag: "High-to-low continuous loop",
    shoulderCoilDegrees: 98,
    contactSpacingMm: 560,
    badge: "Tour Benchmark · Classical 1HB",
    themeColor: "#818cf8",
    stagePoses: {
      ready: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.57, 0.22),
        left_elbow: pt(0.40, 0.35),
        right_elbow: pt(0.60, 0.35),
        left_wrist: pt(0.46, 0.44),
        right_wrist: pt(0.54, 0.49),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.43, 0.72),
        right_knee: pt(0.57, 0.72),
        left_ankle: pt(0.40, 0.92),
        right_ankle: pt(0.60, 0.92),
      },
      unit_turn: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.58, 0.23),
        left_elbow: pt(0.54, 0.34),
        right_elbow: pt(0.68, 0.36),
        left_wrist: pt(0.64, 0.40),
        right_wrist: pt(0.70, 0.42),
        left_hip: pt(0.47, 0.50),
        right_hip: pt(0.55, 0.51),
        left_knee: pt(0.44, 0.73),
        right_knee: pt(0.62, 0.75),
        left_ankle: pt(0.41, 0.92),
        right_ankle: pt(0.65, 0.92),
      },
      backswing: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.58, 0.23),
        left_elbow: pt(0.56, 0.37),
        right_elbow: pt(0.70, 0.40),
        left_wrist: pt(0.66, 0.44),
        right_wrist: pt(0.72, 0.46),
        left_hip: pt(0.46, 0.51),
        right_hip: pt(0.56, 0.52),
        left_knee: pt(0.43, 0.74),
        right_knee: pt(0.63, 0.76),
        left_ankle: pt(0.40, 0.92),
        right_ankle: pt(0.66, 0.92),
      },
      forward_swing_contact: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.57, 0.22),
        left_elbow: pt(0.60, 0.35),
        right_elbow: pt(0.36, 0.32),
        left_wrist: pt(0.70, 0.38),
        right_wrist: pt(0.24, 0.28),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.44, 0.71),
        right_knee: pt(0.56, 0.71),
        left_ankle: pt(0.41, 0.92),
        right_ankle: pt(0.59, 0.92),
      },
      follow_through: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.46, 0.22),
        right_shoulder: pt(0.54, 0.22),
        left_elbow: pt(0.62, 0.36),
        right_elbow: pt(0.30, 0.22),
        left_wrist: pt(0.72, 0.42),
        right_wrist: pt(0.18, 0.16),
        left_hip: pt(0.47, 0.50),
        right_hip: pt(0.53, 0.50),
        left_knee: pt(0.45, 0.71),
        right_knee: pt(0.55, 0.71),
        left_ankle: pt(0.43, 0.92),
        right_ankle: pt(0.57, 0.92),
      },
      recovery: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.57, 0.22),
        left_elbow: pt(0.40, 0.35),
        right_elbow: pt(0.60, 0.35),
        left_wrist: pt(0.46, 0.48),
        right_wrist: pt(0.54, 0.49),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.43, 0.72),
        right_knee: pt(0.57, 0.72),
        left_ankle: pt(0.40, 0.92),
        right_ankle: pt(0.60, 0.92),
      },
    },
    keyDeltas: {
      ready: { joint: "Posture Alignment", targetMetric: "Spine vertical 88°", coachInsight: "Tall, balanced platform with zero tension in shoulders." },
      unit_turn: { joint: "Left Hand Support", targetMetric: "Holds throat until 0.42s", coachInsight: "Non-hitting hand guides the high racket takeback." },
      backswing: { joint: "Elbow Extension", targetMetric: "Near-straight hitting arm", coachInsight: "Preserve spacious radius from chest for maximum leverage." },
      forward_swing_contact: { joint: "Head Fixation", targetMetric: "0.0° head rotation at hit", coachInsight: "Keep eyes glued to contact window while arms open in opposition." },
      follow_through: { joint: "Finish Height", targetMetric: "High classical release", coachInsight: "High chest-high finish extending toward opposite court corner." },
      recovery: { joint: "Footwork Reset", targetMetric: "Balanced glide step", coachInsight: "Re-center seamlessly without hurried emergency strides." },
    },
    telemetryByStage: {
      ready: {
        joint: "Closed Platform Stance",
        athleteValue: "Open stance",
        proValue: "Closed / Neutral stance",
        deltaLabel: "Δ Closed Platform Stance",
        deltaColor: "text-sky-400",
        coachingCue: "Step across to align front hip for classical one-handed leverage.",
        efficiencyLoss: "-8% linear drive",
      },
      unit_turn: {
        joint: "Left Hand Throat Support",
        athleteValue: "Early release (0.15s)",
        proValue: "Holds throat until 0.42s",
        deltaLabel: "Δ Supporting Hand Takeback",
        deltaColor: "text-amber-400",
        coachingCue: "Keep non-hitting hand on racket throat until backswing apex.",
        efficiencyLoss: "-14% upper back coil",
      },
      backswing: {
        joint: "Hitting Arm Radius",
        athleteValue: "Bent elbow radius",
        proValue: "Near-straight hitting arm",
        deltaLabel: "Δ Spacious Arm Radius",
        deltaColor: "text-rose-400",
        coachingCue: "Preserve wide arm radius away from chest for maximum swing leverage.",
        efficiencyLoss: "-15% rotational leverage",
      },
      forward_swing_contact: {
        joint: "Arm Separation & Contact",
        athleteValue: "30cm cramped contact",
        proValue: "56cm with chest expansion",
        deltaLabel: "Δ +26cm Reach & Arm Separation",
        deltaColor: "text-rose-400",
        coachingCue: "“Expand the chest. Open both arms in opposition.”",
        efficiencyLoss: "-22% sweetspot velocity",
      },
      follow_through: {
        joint: "High Classical Release",
        athleteValue: "Low decelerated finish",
        proValue: "High corner extension",
        deltaLabel: "Δ High Corner Extension",
        deltaColor: "text-emerald-400",
        coachingCue: "Release high toward opposite court corner with open chest.",
        efficiencyLoss: "-10% ball depth & trajectory control",
      },
      recovery: {
        joint: "Balanced Glide Step",
        athleteValue: "1.42s recovery",
        proValue: "0.96s balanced glide",
        deltaLabel: "Δ 0.46s Smooth Recovery",
        deltaColor: "text-sky-400",
        coachingCue: "Glide back to center ready platform without rushing.",
        efficiencyLoss: "-8% balance reset",
      },
    },
  },

  sampras_serve: {
    id: "sampras_serve",
    name: "Platform Trophy Power",
    signature: "Platform Stance Vertical Drive",
    applicableActions: ["serve"],
    stanceType: "Universal Platform",
    kineticStrength: "Deep Knee Flexion ➔ Vertical Explosive Drive",
    racketDropLag: "Maximum shoulder-hip separation",
    shoulderCoilDegrees: 112,
    contactSpacingMm: 620,
    badge: "Tour Benchmark · Trophy Serve",
    themeColor: "#f59e0b",
    stagePoses: {
      ready: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.56, 0.22),
        left_elbow: pt(0.42, 0.35),
        right_elbow: pt(0.58, 0.35),
        left_wrist: pt(0.46, 0.48),
        right_wrist: pt(0.54, 0.49),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.44, 0.72),
        right_knee: pt(0.56, 0.72),
        left_ankle: pt(0.42, 0.92),
        right_ankle: pt(0.58, 0.92),
      },
      unit_turn: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.56, 0.23),
        left_elbow: pt(0.42, 0.24),
        right_elbow: pt(0.64, 0.34),
        left_wrist: pt(0.44, 0.12),
        right_wrist: pt(0.68, 0.42),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.51),
        left_knee: pt(0.44, 0.73),
        right_knee: pt(0.58, 0.74),
        left_ankle: pt(0.42, 0.92),
        right_ankle: pt(0.60, 0.92),
      },
      backswing: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.42, 0.20),
        right_shoulder: pt(0.58, 0.24),
        left_elbow: pt(0.40, 0.12),
        right_elbow: pt(0.66, 0.28),
        left_wrist: pt(0.40, 0.04),
        right_wrist: pt(0.68, 0.46),
        left_hip: pt(0.45, 0.51),
        right_hip: pt(0.55, 0.52),
        left_knee: pt(0.42, 0.75),
        right_knee: pt(0.60, 0.77),
        left_ankle: pt(0.41, 0.92),
        right_ankle: pt(0.61, 0.92),
      },
      forward_swing_contact: {
        head: pt(0.50, 0.08),
        left_shoulder: pt(0.44, 0.16),
        right_shoulder: pt(0.56, 0.16),
        left_elbow: pt(0.44, 0.28),
        right_elbow: pt(0.56, 0.08),
        left_wrist: pt(0.44, 0.38),
        right_wrist: pt(0.56, 0.02),
        left_hip: pt(0.46, 0.46),
        right_hip: pt(0.54, 0.46),
        left_knee: pt(0.45, 0.68),
        right_knee: pt(0.55, 0.68),
        left_ankle: pt(0.44, 0.88),
        right_ankle: pt(0.56, 0.88),
      },
      follow_through: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.56, 0.22),
        left_elbow: pt(0.42, 0.32),
        right_elbow: pt(0.40, 0.36),
        left_wrist: pt(0.44, 0.42),
        right_wrist: pt(0.34, 0.54),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.45, 0.72),
        right_knee: pt(0.55, 0.72),
        left_ankle: pt(0.44, 0.92),
        right_ankle: pt(0.56, 0.92),
      },
      recovery: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.56, 0.22),
        left_elbow: pt(0.42, 0.35),
        right_elbow: pt(0.58, 0.35),
        left_wrist: pt(0.46, 0.48),
        right_wrist: pt(0.54, 0.49),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.44, 0.72),
        right_knee: pt(0.56, 0.72),
        left_ankle: pt(0.42, 0.92),
        right_ankle: pt(0.58, 0.92),
      },
    },
    keyDeltas: {
      ready: { joint: "Trophy Setup", targetMetric: "Deep knee bend 110°", coachInsight: "Platform base coiled and loaded into the court." },
      unit_turn: { joint: "Toss Extension", targetMetric: "High vertical toss release", coachInsight: "Left arm reaches straight up placing ball into the court." },
      backswing: { joint: "Trophy Tilt", targetMetric: "Deep back scratch drop", coachInsight: "Right elbow stays high while racket drops behind spine." },
      forward_swing_contact: { joint: "Pronation Extension", targetMetric: "Apex reach at hit", coachInsight: "Drive upwards with explosive forearm pronation." },
      follow_through: { joint: "Landing Balance", targetMetric: "Dominant leg landing", coachInsight: "Absorb landing 2 feet inside baseline." },
      recovery: { joint: "Split-Step", targetMetric: "Instant split on baseline", coachInsight: "Reset ready position before opponent strikes." },
    },
    telemetryByStage: {
      ready: {
        joint: "Knee Loading Flexion",
        athleteValue: "140° shallow bend",
        proValue: "110° deep knee load",
        deltaLabel: "Δ +30° Deep Knee Loading",
        deltaColor: "text-amber-400",
        coachingCue: "Load deeply through both knees to maximize ground force explosion.",
        efficiencyLoss: "-18% ground reaction drive",
      },
      unit_turn: {
        joint: "Toss Arm Verticality",
        athleteValue: "Low lateral toss",
        proValue: "High vertical release",
        deltaLabel: "Δ High Vertical Toss Placement",
        deltaColor: "text-sky-400",
        coachingCue: "Reach straight up with non-dominant arm to place ball consistently into court.",
        efficiencyLoss: "-12% toss consistency",
      },
      backswing: {
        joint: "Cartwheel Shoulder Tilt",
        athleteValue: "Level shoulders",
        proValue: "42° deep shoulder tilt",
        deltaLabel: "Δ Deep Shoulder-Hip Tilt",
        deltaColor: "text-rose-400",
        coachingCue: "Drop hitting shoulder deeply under tossing shoulder for explosive upward drive.",
        efficiencyLoss: "-24% serve whip speed",
      },
      forward_swing_contact: {
        joint: "Apex Contact Reach & Pronation",
        athleteValue: "18cm below full apex",
        proValue: "620mm apex extension",
        deltaLabel: "Δ Full Apex Pronation Reach",
        deltaColor: "text-rose-400",
        coachingCue: "“Reach up at full apex; snap and pronate through the ball.”",
        efficiencyLoss: "-20% serve MPH & angle",
      },
      follow_through: {
        joint: "Court Penetration Landing",
        athleteValue: "Landing on baseline",
        proValue: "2 feet inside baseline",
        deltaLabel: "Δ Inside Baseline Landing",
        deltaColor: "text-emerald-400",
        coachingCue: "Drive up and into the court, absorbing landing inside the baseline.",
        efficiencyLoss: "-15% court penetration",
      },
      recovery: {
        joint: "Instant Split-Step",
        athleteValue: "1.40s reset",
        proValue: "0.88s instant split",
        deltaLabel: "Δ 0.52s Instant Baseline Split",
        deltaColor: "text-sky-400",
        coachingCue: "Reset into ready stance before opponent makes contact with return.",
        efficiencyLoss: "-14% first-ball readiness",
      },
    },
  },

  kick_serve: {
    id: "kick_serve",
    name: "Heavy Topspin Kick",
    signature: "7-to-1 O'clock Angular Brush",
    applicableActions: ["serve", "second_serve", "kick_serve"],
    stanceType: "Universal Platform",
    kineticStrength: "Thoracic Arch Flexion ➔ Vertical Topspin Brush",
    racketDropLag: "Deep spine scratch behind head",
    shoulderCoilDegrees: 116,
    contactSpacingMm: 590,
    badge: "Tour Benchmark · Kick Serve",
    themeColor: "#a855f7",
    stagePoses: {
      ready: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.56, 0.22),
        left_elbow: pt(0.42, 0.35),
        right_elbow: pt(0.58, 0.35),
        left_wrist: pt(0.46, 0.48),
        right_wrist: pt(0.54, 0.49),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.44, 0.72),
        right_knee: pt(0.56, 0.72),
        left_ankle: pt(0.42, 0.92),
        right_ankle: pt(0.58, 0.92),
      },
      unit_turn: {
        head: pt(0.49, 0.12),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.57, 0.23),
        left_elbow: pt(0.41, 0.22),
        right_elbow: pt(0.65, 0.33),
        left_wrist: pt(0.41, 0.08),
        right_wrist: pt(0.68, 0.40),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.51),
        left_knee: pt(0.43, 0.73),
        right_knee: pt(0.59, 0.74),
        left_ankle: pt(0.41, 0.92),
        right_ankle: pt(0.61, 0.92),
      },
      backswing: {
        head: pt(0.49, 0.13),
        left_shoulder: pt(0.41, 0.20),
        right_shoulder: pt(0.59, 0.25),
        left_elbow: pt(0.39, 0.14),
        right_elbow: pt(0.67, 0.26),
        left_wrist: pt(0.39, 0.05),
        right_wrist: pt(0.52, 0.38),
        left_hip: pt(0.44, 0.51),
        right_hip: pt(0.56, 0.52),
        left_knee: pt(0.42, 0.75),
        right_knee: pt(0.61, 0.77),
        left_ankle: pt(0.41, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
      forward_swing_contact: {
        head: pt(0.48, 0.09),
        left_shoulder: pt(0.43, 0.17),
        right_shoulder: pt(0.57, 0.17),
        left_elbow: pt(0.42, 0.30),
        right_elbow: pt(0.51, 0.09),
        left_wrist: pt(0.42, 0.40),
        right_wrist: pt(0.48, 0.03),
        left_hip: pt(0.45, 0.47),
        right_hip: pt(0.55, 0.47),
        left_knee: pt(0.44, 0.69),
        right_knee: pt(0.56, 0.69),
        left_ankle: pt(0.43, 0.88),
        right_ankle: pt(0.57, 0.88),
      },
      follow_through: {
        head: pt(0.49, 0.12),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.57, 0.22),
        left_elbow: pt(0.39, 0.32),
        right_elbow: pt(0.55, 0.30),
        left_wrist: pt(0.38, 0.42),
        right_wrist: pt(0.58, 0.42),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.50),
        left_knee: pt(0.44, 0.71),
        right_knee: pt(0.62, 0.68),
        left_ankle: pt(0.43, 0.90),
        right_ankle: pt(0.68, 0.82),
      },
      recovery: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.44, 0.22),
        right_shoulder: pt(0.56, 0.22),
        left_elbow: pt(0.42, 0.35),
        right_elbow: pt(0.58, 0.35),
        left_wrist: pt(0.46, 0.48),
        right_wrist: pt(0.54, 0.49),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.44, 0.72),
        right_knee: pt(0.56, 0.72),
        left_ankle: pt(0.42, 0.92),
        right_ankle: pt(0.58, 0.92),
      },
    },
    keyDeltas: {
      ready: { joint: "Platform Coil", targetMetric: "115° knee flexion", coachInsight: "Balanced platform coiled to drive upward rather than forward." },
      unit_turn: { joint: "Overhead Toss Placement", targetMetric: "11 o'clock above left shoulder", coachInsight: "Toss slightly behind the head to open the upward brush path." },
      backswing: { joint: "Thoracic Arch Flexion", targetMetric: "38° back extension under ball", coachInsight: "Arch the upper back so your eyes look directly up into the contact window." },
      forward_swing_contact: { joint: "7-to-1 O'clock Brush", targetMetric: "+3,600 RPM brush apex", coachInsight: "Brush up and across the back of the ball from left to right." },
      follow_through: { joint: "Mule Kick Counterbalance", targetMetric: "Right-side deceleration wrap", coachInsight: "Extend rear leg back to counterbalance the upper body arch." },
      recovery: { joint: "Dynamic Split", targetMetric: "0.90s baseline landing split", coachInsight: "Land balanced and ready to move immediately to either corner." },
    },
    telemetryByStage: {
      ready: {
        joint: "Knee Loading Flexion",
        athleteValue: "140° shallow bend",
        proValue: "115° deep knee load",
        deltaLabel: "Δ +25° Deep Vertical Load",
        deltaColor: "text-amber-400",
        coachingCue: "Load deeply through both legs to power vertical topspin trajectory.",
        efficiencyLoss: "-16% vertical jump impulse",
      },
      unit_turn: {
        joint: "Toss Placement Axis",
        athleteValue: "Tossed in front (1 o'clock)",
        proValue: "Overhead (11 o'clock)",
        deltaLabel: "Δ Overhead Toss Placement",
        deltaColor: "text-sky-400",
        coachingCue: "Place toss directly over the left shoulder to allow upward brushing angle.",
        efficiencyLoss: "-22% topspin brush window",
      },
      backswing: {
        joint: "Thoracic Back Arch",
        athleteValue: "Upright spine",
        proValue: "38° lumbar/thoracic arch",
        deltaLabel: "Δ Under-Ball Arch Flexion",
        deltaColor: "text-rose-400",
        coachingCue: "Get your head and hitting shoulder completely underneath the ball.",
        efficiencyLoss: "-24% vertical launch arc",
      },
      forward_swing_contact: {
        joint: "7-to-1 O'clock Brush Reach",
        athleteValue: "Linear forward push",
        proValue: "+3,600 RPM brush apex",
        deltaLabel: "Δ Crown Contact & Upward Brush",
        deltaColor: "text-rose-400",
        coachingCue: "“Brush from 7 to 1 o'clock. Explode up through the back of the ball.”",
        efficiencyLoss: "-26% kick RPM & bounce height",
      },
      follow_through: {
        joint: "Mule Kick Counterbalance",
        athleteValue: "Linear forward fall",
        proValue: "Right-side wrap & mule kick",
        deltaLabel: "Δ Mule Kick Counterbalance",
        deltaColor: "text-emerald-400",
        coachingCue: "Kick rear leg back while racket stays on right side to stabilize spine.",
        efficiencyLoss: "-14% landing balance & recovery",
      },
      recovery: {
        joint: "Instant Baseline Split",
        athleteValue: "1.40s reset",
        proValue: "0.90s balanced split",
        deltaLabel: "Δ 0.50s Fast Landing Reset",
        deltaColor: "text-sky-400",
        coachingCue: "Absorb landing on baseline and split-step instantly for the return.",
        efficiencyLoss: "-12% first-ball readiness",
      },
    },
  },

  edberg_volley: {
    id: "edberg_volley",
    name: "Net Attack Universal",
    signature: "Low Center of Gravity Punch",
    applicableActions: ["forehand_volley", "backhand_volley"],
    stanceType: "Universal Platform",
    kineticStrength: "Punch Through ➔ Low Center of Gravity",
    racketDropLag: "Zero backswing loop",
    shoulderCoilDegrees: 65,
    contactSpacingMm: 420,
    badge: "Tour Benchmark · Net Attack",
    themeColor: "#ec4899",
    stagePoses: {
      ready: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.57, 0.22),
        left_elbow: pt(0.40, 0.34),
        right_elbow: pt(0.60, 0.34),
        left_wrist: pt(0.47, 0.44),
        right_wrist: pt(0.53, 0.45),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.50),
        left_knee: pt(0.42, 0.72),
        right_knee: pt(0.58, 0.72),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
      unit_turn: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.41, 0.22),
        right_shoulder: pt(0.59, 0.23),
        left_elbow: pt(0.43, 0.34),
        right_elbow: pt(0.64, 0.33),
        left_wrist: pt(0.48, 0.42),
        right_wrist: pt(0.68, 0.36),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.51),
        left_knee: pt(0.43, 0.72),
        right_knee: pt(0.59, 0.73),
        left_ankle: pt(0.40, 0.92),
        right_ankle: pt(0.63, 0.92),
      },
      backswing: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.41, 0.22),
        right_shoulder: pt(0.59, 0.23),
        left_elbow: pt(0.43, 0.34),
        right_elbow: pt(0.65, 0.32),
        left_wrist: pt(0.48, 0.42),
        right_wrist: pt(0.69, 0.34),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.51),
        left_knee: pt(0.43, 0.73),
        right_knee: pt(0.60, 0.74),
        left_ankle: pt(0.40, 0.92),
        right_ankle: pt(0.64, 0.92),
      },
      forward_swing_contact: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.57, 0.22),
        left_elbow: pt(0.40, 0.34),
        right_elbow: pt(0.44, 0.32),
        left_wrist: pt(0.42, 0.42),
        right_wrist: pt(0.28, 0.30),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.44, 0.71),
        right_knee: pt(0.56, 0.71),
        left_ankle: pt(0.41, 0.92),
        right_ankle: pt(0.59, 0.92),
      },
      follow_through: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.57, 0.22),
        left_elbow: pt(0.40, 0.34),
        right_elbow: pt(0.40, 0.33),
        left_wrist: pt(0.42, 0.42),
        right_wrist: pt(0.24, 0.34),
        left_hip: pt(0.46, 0.50),
        right_hip: pt(0.54, 0.50),
        left_knee: pt(0.44, 0.71),
        right_knee: pt(0.56, 0.71),
        left_ankle: pt(0.41, 0.92),
        right_ankle: pt(0.59, 0.92),
      },
      recovery: {
        head: pt(0.50, 0.12),
        left_shoulder: pt(0.43, 0.22),
        right_shoulder: pt(0.57, 0.22),
        left_elbow: pt(0.40, 0.34),
        right_elbow: pt(0.60, 0.34),
        left_wrist: pt(0.47, 0.44),
        right_wrist: pt(0.53, 0.45),
        left_hip: pt(0.45, 0.50),
        right_hip: pt(0.55, 0.50),
        left_knee: pt(0.42, 0.72),
        right_knee: pt(0.58, 0.72),
        left_ankle: pt(0.38, 0.92),
        right_ankle: pt(0.62, 0.92),
      },
    },
    keyDeltas: {
      ready: { joint: "Racket Head Height", targetMetric: "Racket tip at chin level", coachInsight: "Keep racket head up and active before the ball crosses the net." },
      unit_turn: { joint: "Shoulder Pivot", targetMetric: "45° quick shoulder turn", coachInsight: "Turn the upper body with zero backswing arm takeaway." },
      backswing: { joint: "Compact Catch", targetMetric: "No backswing behind shoulder", coachInsight: "Set the racket face out in front of the chest." },
      forward_swing_contact: { joint: "Forward Punch", targetMetric: "Firm wrist 90° angle", coachInsight: "Punch through the ball out in front with a solid, unyielding wrist." },
      follow_through: { joint: "Short Deceleration", targetMetric: "Stop racket 12 inches past contact", coachInsight: "Do not follow through like a groundstroke; absorb and hold." },
      recovery: { joint: "Net Re-Split", targetMetric: "Instant split-step forward", coachInsight: "Close into the net for the next ball." },
    },
    telemetryByStage: {
      ready: {
        joint: "Active Racket Height",
        athleteValue: "Low racket head",
        proValue: "Chin-level active racket",
        deltaLabel: "Δ Racket Tip at Chin Level",
        deltaColor: "text-sky-400",
        coachingCue: "Keep racket head up and active to react instantly at the net.",
        efficiencyLoss: "-10% reaction speed",
      },
      unit_turn: {
        joint: "Upper Body Pivot",
        athleteValue: "Arm takeaway drift",
        proValue: "45° quick torso pivot",
        deltaLabel: "Δ Zero Arm Takeaway",
        deltaColor: "text-amber-400",
        coachingCue: "Turn upper body with zero backward arm takeaway.",
        efficiencyLoss: "-16% volley timing",
      },
      backswing: {
        joint: "Compact Front Catch",
        athleteValue: "Racket behind shoulder",
        proValue: "Racket in front of chest",
        deltaLabel: "Δ Compact Chest Catch",
        deltaColor: "text-rose-400",
        coachingCue: "Set racket face out in front of chest; never take racket behind shoulders.",
        efficiencyLoss: "-18% volley stability",
      },
      forward_swing_contact: {
        joint: "Firm Wrist Punch Reach",
        athleteValue: "Loose wrist flick",
        proValue: "420mm firm 90° punch",
        deltaLabel: "Δ Solid 90° Wrist Punch",
        deltaColor: "text-rose-400",
        coachingCue: "“Firm wrist out in front; step and punch through the ball.”",
        efficiencyLoss: "-22% volley depth & pop",
      },
      follow_through: {
        joint: "Short Deceleration Hold",
        athleteValue: "Full groundstroke swing",
        proValue: "12-inch absorption & hold",
        deltaLabel: "Δ 12-Inch Absorption & Hold",
        deltaColor: "text-emerald-400",
        coachingCue: "Stop racket 12 inches past contact to absorb pace and control angle.",
        efficiencyLoss: "-12% rebound control",
      },
      recovery: {
        joint: "Forward Net Re-Split",
        athleteValue: "Standing flatfooted",
        proValue: "Forward net close step",
        deltaLabel: "Δ Forward Net Close Step",
        deltaColor: "text-sky-400",
        coachingCue: "Close two steps tighter to the net immediately after the volley.",
        efficiencyLoss: "-16% closing the net",
      },
    },
  },
};

export function getProArchetypesForAction(actionType: string): ProArchetype[] {
  const normalized = actionType.toLowerCase().replace(/-/g, "_");
  let ids: ProArchetypeId[];

  if (normalized.includes("forehand") && !normalized.includes("volley")) {
    ids = ["alcaraz_forehand", "federer_forehand"];
  } else if (normalized.includes("one_handed") || normalized.includes("one_hand") || normalized.includes("slice")) {
    ids = ["federer_classic", "alcaraz_modern"];
  } else if (normalized.includes("backhand")) {
    ids = ["alcaraz_modern", "djokovic_compact"];
  } else if (normalized.includes("serve")) {
    ids = ["sampras_serve", "kick_serve"];
  } else if (normalized.includes("volley")) {
    ids = ["edberg_volley", "djokovic_compact"];
  } else {
    ids = ["alcaraz_modern", "djokovic_compact"];
  }

  return ids.map((id) => PRO_ARCHETYPES[id]).filter(Boolean);
}
