from __future__ import annotations

from typing import Any


STROKE_GUIDE_VERSION = "complete-tennis-stroke-guide-v1.0.0"
GUIDE_EVIDENCE_ID = "athlete-supplied-complete-stroke-guide"


def _check(body_part: str, area_id: str | None, target: str, *, boundary: str | None = None) -> dict[str, Any]:
    return {
        "bodyPart": body_part,
        "areaId": area_id,
        "target": target,
        "cameraBoundary": boundary,
    }


def _phase(
    phase_id: str,
    label: str,
    cue: str,
    summary: str,
    measurement: str,
    checks: list[dict[str, Any]],
    *,
    phase: str,
    body_region_id: str,
    context_note: str,
    camera_boundary: str,
) -> dict[str, Any]:
    return {
        "id": phase_id,
        "label": label,
        "cue": cue,
        "summary": summary,
        "measurement": measurement,
        "checks": checks,
        "phase": phase,
        "bodyRegionId": body_region_id,
        "contextNote": context_note,
        "cameraBoundary": camera_boundary,
    }


RACKET_LIMIT = "Exact grip, racket-head position, string angle, spin, and ball result need a clear racket-and-ball view or dedicated tracking."
FORCE_LIMIT = "Monocular pose estimates body motion, not ground force, joint torque, muscle activation, or weight percentage."
CONTACT_LIMIT = "The engine uses a likely strike window; exact ball-on-strings contact is not detected."


STROKE_GUIDES: dict[str, dict[str, Any]] = {
    "forehand": {
        "displayName": "Forehand",
        "stylePrinciple": "Judge the forehand against the player's grip, ball height, stance, intention, and recovery demand. Eastern, semi-western, and western grips legitimately create different arm shapes and contact distances.",
        "phases": [
            _phase("ready-position", "Ready position", "Athletic, racket out front.", "Begin balanced, with soft knees and both hands organizing the racket in front while the eyes read the opponent.", "Pose-estimated base width, knee shape, balance point, and early head stability.", [
                _check("Feet & knees", "footwork_base", "Use a balanced shoulder-width starting base with soft knees and pressure ready to move."),
                _check("Hips", "footwork_base", "Begin square enough to react in either direction."),
                _check("Hands & racket", None, "Hold the racket out front with the non-hitting hand supporting the throat.", boundary=RACKET_LIMIT),
                _check("Head & eyes", "body_position", "Keep the head level while reading the opponent's contact."),
            ], phase="preparation", body_region_id="feet", context_note="Ready width should fit the athlete and court position; shoulder-width is a starting reference, not a rigid target.", camera_boundary=RACKET_LIMIT),
            _phase("unit-turn", "Preparation / unit turn", "Turn together; separate late.", "Load the back foot while the hips, shoulders, and racket organize together. Avoid taking the racket back with the arm alone.", "Pose-estimated preparation timing, base change, shoulder–pelvis relationship, and head stability.", [
                _check("Feet & knees", "footwork_base", "Load onto the back or outside foot while preserving adjustment space."),
                _check("Hips", "backlift_preparation", "Turn the hips and shoulders together before the arm tries to swing."),
                _check("Hands & racket", "backlift_preparation", "Let the unit turn carry the racket back instead of pulling it back with the arm alone."),
                _check("Head & eyes", "body_position", "Stay level and track the incoming ball during the turn."),
            ], phase="preparation", body_region_id="backlift", context_note="The size of the turn changes with time available, incoming pace, and intended direction.", camera_boundary=RACKET_LIMIT),
            _phase("backswing-loading", "Backswing / loading", "Plant, load, then drop.", "Plant a usable anchor, flex to the ball height, preserve hip load, and let the hand path organize before acceleration.", "Pose-estimated knee load, base stability, hand-to-torso space, and shoulder–pelvis separation.", [
                _check("Feet & knees", "lower_body_loading", "Plant a stable anchor and flex the knees to match the ball height."),
                _check("Hips", "lower_body_loading", "Keep the hips loaded until the forward sequence begins."),
                _check("Hands", "contact_spacing", "Keep the elbow and hand organized with room in front of the chest."),
                _check("Racket", None, "Confirm the racket drops below the expected ball height with a laid-back wrist before the forward swing.", boundary=RACKET_LIMIT),
                _check("Head & eyes", "body_position", "Keep tracking the bounce without tipping the head away."),
            ], phase="loading", body_region_id="hips", context_note="Open, semi-open, and neutral stances can all work; the plant must still give the rotation a stable base.", camera_boundary=RACKET_LIMIT),
            _phase("forward-swing", "Forward swing", "Legs, hips, trunk, hand.", "Drive from the legs, let the hips initiate the uncoiling, then allow the torso, shoulder, arm, and racket to accelerate in order.", "Pose-estimated knee extension, hip-to-shoulder timing, wrist-speed progression, and head stability.", [
                _check("Feet & knees", "lower_body_extension", "Drive upward and forward only after the loading position is established."),
                _check("Hips", "hand_swing_path", "Let hip rotation lead the shoulders and hitting arm."),
                _check("Hands", "hand_swing_path", "Build speed progressively; do not begin with an isolated arm burst."),
                _check("Head & eyes", "body_position", "Keep the head quiet while the body uncoils underneath it."),
            ], phase="acceleration", body_region_id="hips", context_note="The amount of vertical drive changes with ball height and spin intention, but the sequence should remain ground-up.", camera_boundary=FORCE_LIMIT),
            _phase("contact", "Contact", "Space in front; see the hit.", "Meet the likely strike window with usable space, a supported lower body, and a quiet head while the racket travels through the intended line.", "Pose-estimated hand-to-torso spacing, elbow shape, knee support, trunk position, and head stability around the likely strike window.", [
                _check("Feet & knees", "lower_body_extension", "Stay supported through the strike instead of standing up before contact."),
                _check("Hips", "hand_swing_path", "Allow the hips to open without pulling the head and chest away from the ball."),
                _check("Hands", "contact_spacing", "Preserve grip-appropriate space beside and in front of the hitting-side hip."),
                _check("Racket", None, "Confirm a stable face through contact; create topspin by travelling up through the ball rather than forcing the face downward.", boundary=RACKET_LIMIT),
                _check("Head & eyes", "body_position", "Keep the head still on the strike window until the ball has left."),
            ], phase="contact", body_region_id="head", context_note="Grip changes the valid elbow shape and contact distance; a bent western-grip contact is not automatically a fault.", camera_boundary=f"{CONTACT_LIMIT} {RACKET_LIMIT}"),
            _phase("follow-through", "Follow-through", "Brush through; finish free.", "Let the racket continue up and across with a complete, unforced finish while the hips and shoulders complete their rotation.", "Pose-estimated post-contact hand travel, trunk rotation, knee extension, head release, and balance.", [
                _check("Feet & knees", "lower_body_extension", "Let the leg drive complete into the finish with balance."),
                _check("Hips", "ending_position", "Complete the rotation without losing the base."),
                _check("Hands", "ending_position", "Allow a full hand path rather than decelerating or chopping the finish short."),
                _check("Racket", None, "Confirm a high, grip- and spin-appropriate finish with the wrist remaining extended rather than snapping forward.", boundary=RACKET_LIMIT),
                _check("Head & eyes", "body_position", "Release the head only after the strike window."),
            ], phase="follow_through", body_region_id="finish", context_note="Over-shoulder, wrap, and more extreme topspin finishes can all be functional when the swing stays continuous and balanced.", camera_boundary=RACKET_LIMIT),
            _phase("recovery", "Recovery", "Finish, reset, split.", "Push back toward the appropriate recovery position, re-center the racket, and prepare the next split step.", "Pose-estimated recovery base, balance-point stability, knee shape, and reset timing.", [
                _check("Feet & knees", "footwork_base", "Use the finish momentum to push into the first recovery step."),
                _check("Hips", "ending_position", "Reset the pelvis toward a responsive court position."),
                _check("Hands & racket", None, "Re-center the racket in front for the next shot.", boundary=RACKET_LIMIT),
                _check("Head & eyes", "body_position", "Regain a level visual platform for the opponent's next contact."),
            ], phase="follow_through", body_region_id="feet", context_note="The correct recovery point depends on shot direction, court position, and opponent options; it is not always the geometric center.", camera_boundary="Court geometry and opponent position are not detected."),
        ],
    },
    "one_handed_backhand": {
        "displayName": "One-handed backhand",
        "stylePrinciple": "Preserve early preparation, forward space, head stillness, and a ground-up release. Racket lag and body orientation vary by player and by topspin versus slice intention.",
        "phases": [
            _phase("ready-position", "Ready position", "Balanced; hands ready.", "Start balanced with soft knees, both hands supporting the racket, and the head reading the opponent.", "Pose-estimated base width, knee shape, balance point, and head stability.", [_check("Feet & knees", "footwork_base", "Stay balanced and ready to turn."), _check("Hips", "footwork_base", "Begin square enough to react."), _check("Hands & racket", None, "Support the racket near the throat so the grip change can happen immediately.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Read the opponent's contact from a level head position.")], phase="preparation", body_region_id="feet", context_note="The ready base should fit the athlete and court position.", camera_boundary=RACKET_LIMIT),
            _phase("preparation", "Preparation", "Racket up; turn early.", "Turn the hips and shoulders early, use the non-dominant hand to support the coil, and organize a high take-back before the ball crowds the swing.", "Pose-estimated preparation timing, base change, shoulder–pelvis relationship, and head position.", [_check("Feet & knees", "footwork_base", "Turn or step the back foot early while keeping the knees engaged."), _check("Hips", "backlift_preparation", "Coil the hips and shoulders together before the hitting arm releases."), _check("Hands", "backlift_preparation", "Use the non-dominant hand on the throat to support the turn and racket organization."), _check("Racket", None, "Confirm the eastern-backhand grip is set early and the take-back begins high.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Track the ball over the shoulder without tipping the head away.")], phase="preparation", body_region_id="backlift", context_note="The one-hander has little margin for a late grip change or late turn.", camera_boundary=RACKET_LIMIT),
            _phase("backswing-loading", "Backswing / loading", "Stay flexed; store the release.", "Keep the knees flexed, preserve the coil, and let the racket organize behind the hand before the forward swing.", "Pose-estimated knee load, shoulder–pelvis separation, hand space, and head stability.", [_check("Feet & knees", "lower_body_loading", "Keep the front leg flexed enough to support the later drive."), _check("Hips", "lower_body_loading", "Preserve the loaded body orientation until the forward sequence begins."), _check("Hands", "contact_spacing", "Keep the hitting arm organized with space for later extension."), _check("Racket", None, "Confirm the racket remains above the hand until the late drop and stores a usable, player-specific lag.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Stay locked on the ball through the load.")], phase="loading", body_region_id="hips", context_note="Elite racket lag varies substantially; use it as a player-specific checkpoint, not a universal angle target.", camera_boundary=RACKET_LIMIT),
            _phase("forward-swing", "Forward swing", "Leg drive; elbow leads.", "Move the weight forward, begin the ground-up uncoiling, and let the elbow lead a firm-wrist arm extension.", "Pose-estimated knee extension, hip-to-shoulder timing, elbow path, wrist-speed progression, and head stability.", [_check("Feet & knees", "lower_body_extension", "Drive the front leg upward after the load."), _check("Hips", "hand_swing_path", "Uncoil without spinning the torso open too early."), _check("Hands", "hand_swing_path", "Let the elbow lead slightly while the wrist remains quiet."), _check("Head & eyes", "body_position", "Keep the head still as the arm accelerates.")], phase="acceleration", body_region_id="hands", context_note="A clean one-hander uses rotation and extension without over-rotating through the strike.", camera_boundary=FORCE_LIMIT),
            _phase("contact", "Contact", "Reach through; freeze the view.", "Meet the likely strike at or just in front of the lead foot with near-full arm extension and exceptional head stillness.", "Pose-estimated contact spacing, elbow extension, knee support, trunk orientation, and head stability.", [_check("Feet & knees", "lower_body_extension", "Stay supported by the lead leg through the strike window."), _check("Hips", "body_position", "Preserve a diagonal-to-sideways body line instead of over-rotating away."), _check("Hands", "contact_spacing", "Create a forward, near-full-arm-length contact corridor."), _check("Racket", None, "Confirm a firm wrist and a face matching the intended topspin and direction.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Keep the head absolutely quiet through the strike window.")], phase="contact", body_region_id="head", context_note="Topspin and slice use different body orientation and arm firmness; this phase assumes the selected topspin one-hander.", camera_boundary=f"{CONTACT_LIMIT} {RACKET_LIMIT}"),
            _phase("follow-through", "Follow-through", "Extend, rise, finish high.", "Continue the natural extension up and across into a high finish while the body completes only the rotation the shot requires.", "Pose-estimated post-contact hand travel, knee extension, trunk travel, head release, and balance.", [_check("Feet & knees", "lower_body_extension", "Complete the upward leg drive into balance."), _check("Hips", "ending_position", "Rotate enough to release the shot without spinning through it."), _check("Hands", "ending_position", "Let arm extension and body release carry the hand into a high finish."), _check("Racket", None, "Confirm a natural high finish rather than actively lifting with the wrist.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Release the eyes only after contact.")], phase="follow_through", body_region_id="finish", context_note="The finish may vary with height, direction, and defense, but a low flat collapse often signals lost extension.", camera_boundary=RACKET_LIMIT),
            _phase("recovery", "Recovery", "Reset and split.", "Push off, square the body, re-center the racket, and regain the next ready position.", "Pose-estimated recovery base, balance, knee shape, and reset timing.", [_check("Feet & knees", "footwork_base", "Push out of the finish into the first recovery step."), _check("Hips", "ending_position", "Square toward the next court task."), _check("Hands & racket", None, "Re-center the racket and restore two-hand support.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Return to a level tracking position.")], phase="follow_through", body_region_id="feet", context_note="Recovery direction is tactical and depends on the shot just played.", camera_boundary="Court geometry and opponent position are not detected."),
        ],
    },
    "slice": {
        "displayName": "Slice backhand",
        "stylePrinciple": "Treat the slice as its own high-to-low, firm-wrist, sideways-body stroke—not as a softened topspin backhand. Defensive and attacking slices can use different depth and follow-through length.",
        "phases": [
            _phase("preparation", "Preparation", "Turn early; racket above the ball.", "Turn sideways early with a compact unit turn and organize the racket above the expected contact height.", "Pose-estimated preparation timing, body turn, base, and head stability.", [_check("Feet & knees", "footwork_base", "Turn early and preserve a balanced forward path."), _check("Hips", "backlift_preparation", "Turn with the shoulders and prepare to stay sideways."), _check("Hands", "backlift_preparation", "Use the non-dominant hand to support a compact take-back."), _check("Racket", None, "Confirm a continental grip and a racket position above expected contact.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Track the ball without losing the sideways axis.")], phase="preparation", body_region_id="backlift", context_note="The slice preparation can resemble a topspin one-hander, but the later path and body release are different.", camera_boundary=RACKET_LIMIT),
            _phase("backswing", "Backswing", "Compact and firm.", "Keep the knees engaged and the body sideways while the racket stays compact behind the ball line.", "Pose-estimated knee shape, trunk orientation, arm space, and head stability.", [_check("Feet & knees", "lower_body_loading", "Stay engaged under the ball rather than standing rigid."), _check("Hips", "body_position", "Preserve the sideways orientation."), _check("Hands", "contact_spacing", "Keep the hitting arm organized and the non-dominant hand supporting the frame."), _check("Racket", None, "Confirm a compact take-back without a large topspin loop.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Stay visually locked on the ball.")], phase="loading", body_region_id="hips", context_note="A compact backswing protects timing and control, especially under pace.", camera_boundary=RACKET_LIMIT),
            _phase("forward-swing", "Forward swing", "Forward and down; stay sideways.", "Move the weight forward while keeping the hips relatively closed and sending a firm arm on a high-to-low path.", "Pose-estimated forward transfer, trunk orientation, hand path, acceleration rhythm, and head stability.", [_check("Feet & knees", "footwork_base", "Transfer forward through a stable lead side."), _check("Hips", "body_position", "Stay relatively sideways instead of rotating like a topspin groundstroke."), _check("Hands", "hand_swing_path", "Build a controlled high-to-low path rather than chopping suddenly."), _check("Racket", None, "Confirm a firm wrist and forearm supination through the path.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Keep tracking into the strike window.")], phase="acceleration", body_region_id="hands", context_note="The swing travels down through the back of the ball, but it should still extend forward rather than stop at contact.", camera_boundary=RACKET_LIMIT),
            _phase("contact", "Contact", "Firm, in front, eyes still.", "Meet the likely strike just in front of the lead knee with a firm arm, quiet head, and sideways body.", "Pose-estimated hand spacing, elbow shape, trunk orientation, lead-side support, and head stability.", [_check("Feet & knees", "footwork_base", "Keep the lead side supported while weight moves forward."), _check("Hips", "body_position", "Hold the sideways body line through contact."), _check("Hands", "contact_spacing", "Use a firm, extended contact corridor in front of the lead knee."), _check("Racket", None, "Confirm a slightly open face and controlled supination rather than a floppy wrist.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Keep the head on contact until the ball leaves.")], phase="contact", body_region_id="head", context_note="The slice contact is generally earlier than the topspin backhand's contact.", camera_boundary=f"{CONTACT_LIMIT} {RACKET_LIMIT}"),
            _phase("follow-through", "Follow-through", "Drive down the court; split the arms.", "Continue the racket down the target line while the non-dominant arm separates behind for balance and the torso stays comparatively sideways.", "Pose-estimated post-contact hand separation, hand travel, trunk travel, head release, and balance.", [_check("Feet & knees", "ending_position", "Continue forward into a balanced finish."), _check("Hips", "body_position", "Avoid rotating fully open like a topspin shot."), _check("Hands", "ending_position", "Let the non-dominant hand split away behind the body for balance."), _check("Racket", None, "Confirm the hitting wrist and arm stay firm to the end of the compact finish.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Release naturally only after contact.")], phase="follow_through", body_region_id="finish", context_note="The slice finish drives more down the court and less up across the body than a topspin backhand.", camera_boundary=RACKET_LIMIT),
            _phase("recovery", "Recovery", "Push, reset, split.", "Push off from the finish, re-center the racket, and recover for the next ball or continue an approach.", "Pose-estimated recovery base, balance, and reset timing.", [_check("Feet & knees", "footwork_base", "Recover from the forward transfer without an extra balance step."), _check("Hips", "ending_position", "Reset for the next court task."), _check("Hands & racket", None, "Re-center the racket after the arm split.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Return to a level tracking position.")], phase="follow_through", body_region_id="feet", context_note="A slice may be a neutral rally ball, defensive reset, or attacking approach; recovery must match the intention.", camera_boundary="Court geometry and opponent position are not detected."),
        ],
    },
    "serve": {
        "displayName": "Serve",
        "stylePrinciple": "Use the eight-stage serve sequence to judge rhythm and chain order while allowing platform or pinpoint stance, serve type, and individual loading depth to vary.",
        "phases": [
            _phase("stance", "Stance", "Side-on; continental; relaxed.", "Begin side-on with a balanced base, continental grip, and a calm visual target.", "Pose-estimated base width, body orientation, balance, and head position.", [_check("Feet & knees", "footwork_base", "Set a balanced platform or pinpoint starting base."), _check("Hips & shoulders", "backlift_preparation", "Begin side-on to create room for coil."), _check("Hands & racket", None, "Confirm a continental grip before the motion starts.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Set the target, then prepare to track the toss.")], phase="preparation", body_region_id="feet", context_note="Platform and pinpoint stances are both valid when balance and timing remain repeatable.", camera_boundary=RACKET_LIMIT),
            _phase("wind-up-toss", "Wind-up / toss", "Lift together; track it.", "Let both arms rise together as the toss arm stays long and the weight moves through a smooth loading rhythm.", "Pose-estimated arm lift, knee flexion, balance-point travel, shoulder line, and head tracking.", [_check("Feet & knees", "lower_body_loading", "Begin the knee load without swaying out of the base."), _check("Hips & shoulders", "backlift_preparation", "Build the coil while the weight shifts smoothly."), _check("Hands", "hand_swing_path", "Coordinate the tossing and hitting arms instead of rushing one ahead."), _check("Racket / toss", None, "Confirm a straight lifting toss arm and a release around eye-to-forehead height.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Track the toss continuously.")], phase="preparation", body_region_id="hands", context_note="Toss location varies by flat, slice, or kick intention; consistency matters more than one universal point.", camera_boundary="Ball toss location and release quality require ball tracking."),
            _phase("trophy-position", "Trophy position", "Coil, bend, eyes up.", "Reach a balanced knee bend and full shoulder coil with the hitting elbow organized and the toss arm extended.", "Pose-estimated knee load, shoulder line, elbow position, trunk posture, and head angle.", [_check("Feet & knees", "lower_body_loading", "Reach a stable, player-appropriate maximum load."), _check("Hips & shoulders", "backlift_preparation", "Complete the coil with the hitting shoulder below the tossing shoulder."), _check("Hands", "contact_spacing", "Keep the hitting elbow bent and raised while the tossing arm stays extended."), _check("Racket", None, "Confirm a controlled, slightly diagonal racket position rather than a collapsed waiter's-tray face.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Keep looking up at the toss.")], phase="loading", body_region_id="backlift", context_note="Knee bend depth and racket angle vary; avoid forcing an extreme pose that disrupts rhythm.", camera_boundary=RACKET_LIMIT),
            _phase("racket-drop", "Racket drop", "Drop as the legs drive.", "Let the racket fall behind the back as the hips begin to lead and the legs prepare to release upward.", "Pose-estimated knee sequence, hip-to-shoulder timing, elbow path, hand path, and head position.", [_check("Feet & knees", "lower_body_extension", "Begin the upward leg drive after the load."), _check("Hips & shoulders", "hand_swing_path", "Let the hips start the uncoiling before the arm accelerates."), _check("Hands", "hand_swing_path", "Keep the hitting arm loose enough for the racket to lag."), _check("Racket", None, "Confirm a real racket drop behind the back without opening into a waiter's tray.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Stay up on the toss and contact point.")], phase="loading", body_region_id="hands", context_note="Racket drop is timed with the leg release; forcing it independently can break the chain.", camera_boundary=RACKET_LIMIT),
            _phase("acceleration", "Acceleration / uncoiling", "Legs, hips, shoulder, elbow.", "Drive up and forward, let hips and shoulders release in sequence, and allow the elbow to lead a loose-to-fast racket path.", "Pose-estimated knee extension, upward body travel, hip-to-shoulder timing, elbow path, and wrist-speed progression.", [_check("Feet & knees", "lower_body_extension", "Drive explosively up and forward after loading."), _check("Hips & shoulders", "hand_swing_path", "Release hips, shoulders, then arm rather than overarming from the start."), _check("Hands", "hand_swing_path", "Let the elbow lead while the wrist stays loose."), _check("Head & eyes", "body_position", "Keep the head up on the contact point.")], phase="acceleration", body_region_id="hands", context_note="The often-taught 45-degree drive is an intention, not a lab-measured requirement in monocular video.", camera_boundary=FORCE_LIMIT),
            _phase("contact", "Contact", "Reach up; pronate through.", "Reach full-body extension slightly in front while the forearm turns through contact and the head remains up.", "Pose-estimated body extension, elbow extension, hand position, trunk angle, and head stability around the likely strike window.", [_check("Feet & knees", "lower_body_extension", "Reach upward extension through the strike window."), _check("Hips & shoulders", "body_position", "Stay organized underneath the reaching arm."), _check("Hands", "contact_spacing", "Create a fully extended overhead contact corridor slightly in front."), _check("Racket", None, "Confirm edge-led acceleration and natural forearm pronation rather than a wrist snap.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Keep the head up until the ball leaves the strings.")], phase="contact", body_region_id="head", context_note="Serve direction and type alter toss and contact details; head stability and upward reach remain high-value checks.", camera_boundary=f"{CONTACT_LIMIT} {RACKET_LIMIT}"),
            _phase("follow-through", "Follow-through", "Pronate, release, decelerate.", "Allow the racket to continue down and across so the arm decelerates naturally instead of stopping abruptly.", "Pose-estimated post-contact hand travel, trunk travel, head release, and balance.", [_check("Feet & knees", "ending_position", "Prepare for a balanced landing rather than collapsing backward."), _check("Hips & shoulders", "ending_position", "Let the torso complete its forward release."), _check("Hands", "ending_position", "Continue the arm path down and across without an abrupt stop."), _check("Racket", None, "Confirm pronation continues after contact into a free deceleration.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Begin lowering the head only after contact.")], phase="follow_through", body_region_id="finish", context_note="A free deceleration protects rhythm and avoids unnecessary shoulder load; this is educational, not an injury diagnosis.", camera_boundary=RACKET_LIMIT),
            _phase("landing-recovery", "Landing / recovery", "Land inside; find ready.", "Land balanced on the front foot, let the back leg counterbalance, and organize the next split step.", "Pose-estimated landing base, balance-point travel, knee control, and reset timing.", [_check("Feet & knees", "footwork_base", "Land on the front foot in balance and absorb the landing."), _check("Hips & shoulders", "ending_position", "Carry the body into the court without falling sideways."), _check("Hands & racket", None, "Re-center the racket after deceleration.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Recover visual balance for the return.")], phase="follow_through", body_region_id="feet", context_note="The exact landing location depends on serve type and player style; compare the athlete with their own repeatable pattern.", camera_boundary="The baseline and opponent response may not be visible."),
        ],
    },
    "forehand_volley": {
        "displayName": "Forehand volley",
        "stylePrinciple": "A volley is a compact intercept, not a shortened groundstroke. Control comes from early readiness, a small shoulder set, forward transfer, and a firm, brief hand path.",
        "phases": [
            _phase("ready-position", "Ready position", "Hands up; weight forward.", "Start on the balls of the feet with soft knees and the racket in front like a boxer ready to block.", "Pose-estimated base, knee shape, hand position, balance, and head stability.", [_check("Feet & knees", "footwork_base", "Stay light, balanced, and slightly forward."), _check("Hands & racket", "backlift_preparation", "Keep the hands and racket visibly in front of the torso."), _check("Head & eyes", "body_position", "Read the opponent's contact.")], phase="preparation", body_region_id="feet", context_note="Net distance and incoming pace change the exact ready height.", camera_boundary=RACKET_LIMIT),
            _phase("split-step", "Split step", "Land as they hit.", "Time a small split to the opponent's contact and land balanced enough to move in either direction.", "Pose-estimated base change, knee flexion, balance-point travel, and head stability.", [_check("Feet & knees", "footwork_base", "Land the split slightly wider and balanced at the opponent's strike."), _check("Hands & racket", "backlift_preparation", "Keep the racket in front during the hop."), _check("Head & eyes", "body_position", "Keep tracking without bobbing away from the ball line.")], phase="preparation", body_region_id="feet", context_note="Opponent-contact timing is a coaching confirmation unless the opponent is also visible.", camera_boundary="The engine does not detect the opponent's contact timing."),
            _phase("preparation", "Preparation", "Set, do not swing.", "Use only a small shoulder turn and keep the hitting hand within the chest width—no groundstroke backswing.", "Pose-estimated preparation duration, hand-to-torso position, elbow path, and head stability.", [_check("Feet & knees", "footwork_base", "Make only the adjustment needed while staying light."), _check("Hands", "backlift_preparation", "Keep the hitting hand in front and the elbow from drifting behind the torso."), _check("Racket", None, "Confirm a continental grip and a laid-back, slightly open racket face.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Track the incoming ball.")], phase="loading", body_region_id="hands", context_note="The biggest volley preparation fault is any real backswing.", camera_boundary=RACKET_LIMIT),
            _phase("contact", "Contact", "Step, punch, see it.", "Step the lead leg into the ball and use a short compact push with a firm wrist and quiet head.", "Pose-estimated forward step, hand spacing, elbow shape, balance, and head stability.", [_check("Feet & knees", "footwork_base", "Step forward through a stable half-lunge."), _check("Hands", "contact_spacing", "Contact in front with a short push rather than a swing."), _check("Racket", None, "Confirm a firm wrist and a slightly open face.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Keep the head still on contact.")], phase="contact", body_region_id="hands", context_note="Incoming ball pace supplies much of the energy; extra swing length usually reduces control.", camera_boundary=f"{CONTACT_LIMIT} {RACKET_LIMIT}"),
            _phase("follow-through", "Follow-through", "Punch and hold.", "Transfer through the front leg and stop with a deliberately compact, held finish.", "Pose-estimated hand travel, forward transfer, trunk stability, and balance.", [_check("Feet & knees", "ending_position", "Continue the weight transfer through the lead leg."), _check("Hands", "ending_position", "Keep the follow-through compact and controlled."), _check("Racket", None, "Confirm the racket holds its line instead of flipping or wrapping.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Release only after the ball has left.")], phase="follow_through", body_region_id="finish", context_note="Unlike a groundstroke, the volley intentionally uses a short punch-and-hold finish.", camera_boundary=RACKET_LIMIT),
            _phase("recovery", "Recovery", "Re-center and split.", "Take a small recovery step, stay forward, and re-center the racket for the next volley.", "Pose-estimated recovery base, balance, and reset timing.", [_check("Feet & knees", "footwork_base", "Recover with a small step or split while staying forward."), _check("Hands & racket", "ending_position", "Return the racket to the center in front."), _check("Head & eyes", "body_position", "Find the next ball immediately.")], phase="follow_through", body_region_id="feet", context_note="At net, recovery is usually compact and forward rather than a retreat to baseline center.", camera_boundary="Opponent and court geometry are not detected."),
        ],
    },
    "backhand_volley": {
        "displayName": "Backhand volley",
        "stylePrinciple": "Keep the less naturally strong side supported: compact shoulder preparation, non-dominant hand on the throat longer, forward weight transfer, and a firm punch-and-hold path.",
        "phases": [
            _phase("ready-position", "Ready position", "Racket in front; stay light.", "Begin in the same balanced net-ready stance with the racket out front and eyes on the opponent.", "Pose-estimated base, knee shape, hand position, balance, and head stability.", [_check("Feet & knees", "footwork_base", "Stay balanced on the balls of the feet."), _check("Hands & racket", "backlift_preparation", "Hold the racket out in front with two-hand support."), _check("Head & eyes", "body_position", "Track the opponent's contact.")], phase="preparation", body_region_id="feet", context_note="Ready height varies with net position and anticipated ball height.", camera_boundary=RACKET_LIMIT),
            _phase("preparation", "Preparation", "Turn, support, set.", "Turn slightly sideways, set the forearm and racket near head height, and keep the non-dominant hand supporting the throat.", "Pose-estimated preparation duration, shoulder turn, hand position, elbow path, and head stability.", [_check("Feet & knees", "footwork_base", "Stay light while turning slightly sideways."), _check("Hips & shoulders", "backlift_preparation", "Align the shoulders toward the intended target without a large swing."), _check("Hands", "backlift_preparation", "Keep the non-dominant hand on the throat longer for support."), _check("Racket", None, "Confirm continental grip and an approximately 45-degree laid-back setup.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Track the incoming ball.")], phase="loading", body_region_id="hands", context_note="The non-dominant hand provides important frame stability on this side.", camera_boundary=RACKET_LIMIT),
            _phase("contact", "Contact", "Step in; push through.", "Step forward with the right foot for a right-handed player, keep contact in front, and avoid leaning backward.", "Pose-estimated forward step, trunk lean, hand spacing, elbow shape, and head stability.", [_check("Feet & knees", "footwork_base", "Step forward with the opposite foot and keep the base underneath the torso."), _check("Hips & shoulders", "body_position", "Stay forward rather than leaning away from contact."), _check("Hands", "contact_spacing", "Use a short push through a contact corridor in front of the torso."), _check("Racket", None, "Confirm a firm wrist and stable face.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Keep the head still through contact.")], phase="contact", body_region_id="hands", context_note="This is a compact block-through action, not a one-handed groundstroke swing.", camera_boundary=f"{CONTACT_LIMIT} {RACKET_LIMIT}"),
            _phase("follow-through", "Follow-through", "Punch and hold.", "Transfer forward through the lead leg and keep the arm path compact with a firm wrist.", "Pose-estimated hand travel, forward transfer, trunk position, and balance.", [_check("Feet & knees", "ending_position", "Complete the forward transfer without falling backward."), _check("Hands", "ending_position", "Hold a compact finish instead of sweeping across the body."), _check("Racket", None, "Confirm the wrist and face stay stable to the end.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Release after contact.")], phase="follow_through", body_region_id="finish", context_note="A deliberately short finish preserves control on the volley.", camera_boundary=RACKET_LIMIT),
            _phase("recovery", "Recovery", "Re-center and split.", "Re-center the racket and regain the balanced net-ready position.", "Pose-estimated recovery base, balance, and reset timing.", [_check("Feet & knees", "footwork_base", "Recover with a small step or split."), _check("Hands & racket", "ending_position", "Return the racket to the center with two-hand support."), _check("Head & eyes", "body_position", "Track the next ball immediately.")], phase="follow_through", body_region_id="feet", context_note="Net recovery is compact and must preserve forward court position.", camera_boundary="Opponent and court geometry are not detected."),
        ],
    },
    "overhead": {
        "displayName": "Overhead smash",
        "stylePrinciple": "Use serve-like acceleration after immediate lob recognition, but move directly into a compact trophy setup. Footwork and uninterrupted ball tracking are as important as the arm swing.",
        "phases": [
            _phase("recognition-footwork", "Recognition & footwork", "Turn, cross, point.", "Turn sideways immediately, use running crossover steps, move behind the projected contact, and keep the non-dominant arm pointing to the ball.", "Pose-estimated turn timing, crossover foot pattern, base travel, non-dominant arm position, and head stability.", [_check("Feet & knees", "footwork_base", "Use running crossover steps and position behind the projected strike."), _check("Hips & shoulders", "backlift_preparation", "Turn sideways while moving to load the body."), _check("Hands", "backlift_preparation", "Keep the non-dominant arm raised as a tracking and coil aid."), _check("Racket", None, "Confirm a continental grip before acceleration.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Lock on the ball throughout its flight.")], phase="preparation", body_region_id="feet", context_note="Crossover steps reduce eye-level bobbing compared with repeated side shuffles.", camera_boundary="Ball flight and projected landing require ball tracking."),
            _phase("trophy-position", "Trophy position", "Set directly; stay under it.", "Set the feet, flex the knees, coil the shoulders, and move directly into a compact trophy position.", "Pose-estimated base, knee load, shoulder line, elbow position, and head angle.", [_check("Feet & knees", "lower_body_loading", "Set a balanced base with enough knee flexion for the required drive or jump."), _check("Hips & shoulders", "backlift_preparation", "Complete the shoulder coil."), _check("Hands", "contact_spacing", "Keep the elbow organized and the non-dominant arm up."), _check("Racket", None, "Move directly to a racket position near head height without a serve-style preparation loop.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Stay fixed on the ball.")], phase="loading", body_region_id="backlift", context_note="A deep lob may require a jump or scissor-kick; the setup must still preserve balance and tracking.", camera_boundary=RACKET_LIMIT),
            _phase("acceleration", "Acceleration", "Legs, hips, elbow, racket.", "Drive from the legs, uncoil the hips and torso, and let the elbow lead a progressively faster overhead path.", "Pose-estimated knee extension, hip-to-shoulder timing, elbow path, wrist-speed progression, and head stability.", [_check("Feet & knees", "lower_body_extension", "Drive or jump after the load rather than swinging with the arm alone."), _check("Hips & shoulders", "hand_swing_path", "Uncoil from the body into the arm."), _check("Hands", "hand_swing_path", "Build speed progressively with the elbow leading."), _check("Head & eyes", "body_position", "Keep the eyes fixed on the contact point.")], phase="acceleration", body_region_id="hands", context_note="The overhead uses the serve's ground-up power chain but a shorter preparation.", camera_boundary=FORCE_LIMIT),
            _phase("contact", "Contact", "Reach high; see it through.", "Shift forward, reach full extension at the highest comfortable point, and meet the likely strike with the head still up.", "Pose-estimated body and elbow extension, hand position, trunk angle, weight-transfer proxy, and head stability.", [_check("Feet & knees", "lower_body_extension", "Transfer from back to front while reaching upward."), _check("Hips & shoulders", "body_position", "Stay organized at roughly a diagonal to the net."), _check("Hands", "contact_spacing", "Create full overhead extension without letting the ball fall too low."), _check("Racket", None, "Confirm contact on top of the ball with natural forearm pronation.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Track the ball through contact to prevent a mishit.")], phase="contact", body_region_id="head", context_note="Take the ball aggressively at a high comfortable point rather than backing up until it drops.", camera_boundary=f"{CONTACT_LIMIT} {RACKET_LIMIT}"),
            _phase("follow-through", "Follow-through", "Down, across, balanced.", "Let the racket travel down and across in a compact deceleration while the body completes its forward release.", "Pose-estimated post-contact hand travel, trunk travel, head release, and balance.", [_check("Feet & knees", "ending_position", "Prepare a balanced landing after the drive or jump."), _check("Hips & shoulders", "ending_position", "Complete the uncoiling without falling away."), _check("Hands", "ending_position", "Allow a compact path toward the opposite hip instead of stopping abruptly."), _check("Racket", None, "Confirm continued pronation and natural deceleration.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Release only after contact.")], phase="follow_through", body_region_id="finish", context_note="The overhead finish is usually more compact than the serve because its preparation is shorter.", camera_boundary=RACKET_LIMIT),
            _phase("recovery", "Recovery", "Land, balance, recover.", "Land under control, re-center the racket, and recover toward the net or the appropriate base position.", "Pose-estimated landing base, balance-point stability, knee control, and reset timing.", [_check("Feet & knees", "footwork_base", "Land balanced, including after a scissor-kick pattern."), _check("Hips & shoulders", "ending_position", "Regain an athletic body position."), _check("Hands & racket", None, "Re-center the racket after deceleration.", boundary=RACKET_LIMIT), _check("Head & eyes", "body_position", "Find the opponent and next ball.")], phase="follow_through", body_region_id="feet", context_note="Recovery may continue forward at net or retreat toward base depending on the point.", camera_boundary="Court geometry and opponent position are not detected."),
        ],
    },
}


ACTION_ALIASES = {
    "backhand": "one_handed_backhand",
    "backhand_slice": "slice",
}


def guide_for(action_type: str) -> dict[str, Any] | None:
    return STROKE_GUIDES.get(ACTION_ALIASES.get(action_type, action_type))

