const beats = [
  {id:"B1_ORIENT",frame:0,caption:"Watch the whole setup first.",ghost:false,link:false,corridor:false},
  {id:"B2_CAUSE",frame:1,caption:"Space starts disappearing here.",ghost:true,link:false,corridor:true},
  {id:"B3_LINK",frame:1,caption:"That leaves fewer contact options.",ghost:true,link:true,corridor:true},
  {id:"B4_EFFECT",frame:2,caption:"Now contact becomes crowded.",ghost:true,link:true,corridor:false},
  {id:"B5_CORRECTION",frame:1,caption:"Keep adjusting before you swing.",ghost:true,link:false,corridor:true},
  {id:"B6_CLEAN",frame:2,caption:"Now watch it with one cue.",ghost:false,link:false,corridor:false}
];
const canvas=document.querySelector("#story"),ctx=canvas.getContext("2d"),caption=document.querySelector("#caption"),status=document.querySelector("#status"),buttons=document.querySelector("#beats");
const noise=document.querySelector("#noise"),confidence=document.querySelector("#confidence"),noiseValue=document.querySelector("#noiseValue"),confidenceValue=document.querySelector("#confidenceValue");
let data,currentBeat=0;
for(const [index,beat] of beats.entries()){const button=document.createElement("button");button.textContent=`${index+1}. ${beat.id.replace(/^B\d_/,"").replaceAll("_"," ")}`;button.onclick=()=>{currentBeat=index;render()};buttons.append(button)}
function point(raw,name,seed){const item=raw.landmarks[name];if(!item||item[2]<Number(confidence.value)/100)return null;const jitter=Number(noise.value)/100;return{x:(item[0]+Math.sin(seed*17+name.length)*jitter)*canvas.width,y:(item[1]+Math.cos(seed*11+name.length)*jitter)*canvas.height,c:item[2]}}
function pose(frame,color,dashed,seed){ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=5;ctx.setLineDash(dashed?[10,8]:[]);for(const [a,b] of data.connections){const p1=point(frame,a,seed),p2=point(frame,b,seed+1);if(!p1||!p2)continue;ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke()}for(const name of Object.keys(frame.landmarks)){const p=point(frame,name,seed+2);if(!p)continue;ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill()}ctx.restore()}
function render(){if(!data)return;const beat=beats[currentBeat],actual=data.repetitions.current[beat.frame],best=data.repetitions.self_best[beat.frame];ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#172033";ctx.fillRect(0,0,canvas.width,canvas.height*.62);ctx.fillStyle="#163526";ctx.fillRect(0,canvas.height*.62,canvas.width,canvas.height*.38);ctx.strokeStyle="#64748b";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,canvas.height*.78);ctx.lineTo(canvas.width,canvas.height*.78);ctx.stroke();if(beat.corridor){ctx.fillStyle="rgba(56,189,248,.13)";ctx.strokeStyle="#38bdf8";ctx.setLineDash([8,8]);ctx.fillRect(canvas.width*.50,canvas.height*.23,canvas.width*.20,canvas.height*.66);ctx.strokeRect(canvas.width*.50,canvas.height*.23,canvas.width*.20,canvas.height*.66);ctx.setLineDash([])}if(beat.ghost)pose(best,"rgba(167,139,250,.72)",true,2);pose(actual,"#38bdf8",false,1);if(beat.link){const root=point(actual,"right_hip",3),effect=point(actual,"right_wrist",4);if(root&&effect){ctx.strokeStyle="#fbbf24";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(root.x,root.y);ctx.quadraticCurveTo((root.x+effect.x)/2,root.y-90,effect.x,effect.y);ctx.stroke();ctx.fillStyle="#fbbf24";ctx.beginPath();ctx.arc(effect.x,effect.y,8,0,Math.PI*2);ctx.fill()}}caption.textContent=beat.caption;[...buttons.children].forEach((button,index)=>button.setAttribute("aria-current",String(index===currentBeat)));noiseValue.textContent=`${noise.value}%`;confidenceValue.textContent=`${confidence.value}%`;const visible=Object.values(actual.landmarks).filter(item=>item[2]>=Number(confidence.value)/100).length;status.textContent=`Beat ${currentBeat+1}/6 · ${visible}/${Object.keys(actual.landmarks).length} landmarks visible · event ${Object.keys(data.events)[beat.frame]}`}
noise.oninput=render;confidence.oninput=render;
fetch("visual_story_keypoints.synthetic.json").then(response=>{if(!response.ok)throw new Error(`fixture ${response.status}`);return response.json()}).then(value=>{data=value;render()}).catch(error=>{status.textContent=`Unable to load keypoint fixture: ${error.message}`;status.style.color="#fda4af"});
