import type { SportDefinition, SportId } from "@/lib/sports/types";

export const sportRegistry: Record<SportId, SportDefinition> = {
  tennis: {
    id: "tennis",
    name: "Tennis",
    shortName: "Tennis",
    description: "Stroke mechanics, serve intelligence, movement, balance, and match development.",
    icon: "🎾",
    heroHeadline: "Build a better tennis stroke with AI",
    heroDescription: "Analyze forehands, backhands, serves, volleys, footwork, and match movement against tennis-specific biomechanical standards.",
    coachingFocus: ["Contact point and kinetic-chain timing", "Balance, recovery, and repeatability"],
    filmingTips: ["Keep the full body, racket, and contact zone in frame.", "Film from behind the baseline or from the side at waist height.", "Use good lighting and avoid digital zoom."],
    participantLabel: "player",
    venueLabel: "court",
    actions: [
      { id: "forehand", label: "Forehand", category: "stroke" },
      { id: "one_handed_backhand", label: "One-handed backhand", category: "stroke" },
      { id: "two_handed_backhand", label: "Two-handed backhand", category: "stroke" },
      { id: "serve", label: "Serve", category: "serve" },
      { id: "forehand_volley", label: "Forehand volley", category: "stroke" },
      { id: "backhand_volley", label: "Backhand volley", category: "stroke" },
      { id: "slice", label: "Slice", category: "stroke" },
      { id: "overhead", label: "Overhead", category: "stroke" },
    ],
    profileGoals: ["Improve consistency", "Generate more power", "Improve footwork", "Improve match play"],
    rankingSystems: ["NTRP", "UTR", "ATP", "WTA", "ITF", "AITA", "Other"],
    biomechanics: ["shoulder rotation", "hip rotation", "contact point", "weight transfer", "follow-through", "recovery"],
    roleOptions: ["Singles", "Doubles", "Singles and doubles"],
    playingStyleOptions: ["All-court", "Aggressive baseline", "Counterpunching", "Serve-and-volley", "Developing"],
    enabled: true,
  },
  badminton: {
    id: "badminton",
    name: "Badminton",
    shortName: "Badminton",
    description: "Overhead technique, racket preparation, footwork, recovery, and court coverage.",
    icon: "🏸",
    heroHeadline: "Sharpen every badminton movement with AI",
    heroDescription: "Break down smashes, clears, drops, serves, net play, and court coverage using badminton-specific sequencing and recovery cues.",
    coachingFocus: ["Overhead sequencing and racket acceleration", "Split step, lunging, and base recovery"],
    filmingTips: ["Capture the full court area used in the movement.", "Keep the racket and both feet visible throughout the clip.", "Film from the rear court or a clear side angle."],
    participantLabel: "player",
    venueLabel: "court",
    actions: [
      { id: "forehand_clear", label: "Forehand clear", category: "stroke" },
      { id: "backhand_clear", label: "Backhand clear", category: "stroke" },
      { id: "smash", label: "Smash", category: "stroke" },
      { id: "drop_shot", label: "Drop shot", category: "shot" },
      { id: "forehand_serve", label: "Forehand serve", category: "serve" },
      { id: "backhand_serve", label: "Backhand serve", category: "serve" },
      { id: "net_shot", label: "Net shot", category: "shot" },
      { id: "drive", label: "Drive", category: "stroke" },
      { id: "other", label: "Other / Not sure", category: "movement" },
    ],
    profileGoals: ["Improve overhead technique", "Increase smash power", "Improve court movement", "Improve consistency"],
    rankingSystems: ["BWF", "National ranking", "Club level", "School/college", "Other"],
    biomechanics: ["scapular loading", "elbow extension", "wrist acceleration", "lunge mechanics", "split step", "recovery"],
    roleOptions: ["Singles", "Doubles", "Mixed doubles", "Multiple formats"],
    playingStyleOptions: ["Attacking", "Defensive", "Counter-attacking", "All-round", "Developing"],
    enabled: false,
  },
  squash: {
    id: "squash",
    name: "Squash",
    shortName: "Squash",
    description: "Compact swing paths, racket preparation, lunging, recovery, and movement efficiency.",
    icon: "🎾",
    heroHeadline: "Move and strike more efficiently in squash",
    heroDescription: "Evaluate compact swing mechanics, lunging, balance, and T-position recovery with a squash-aware coaching model.",
    coachingFocus: ["Racket preparation and compact swing path", "Lunge control and T-position recovery"],
    filmingTips: ["Place the camera safely behind the back glass when possible.", "Keep the player and T area visible.", "Record several repetitions rather than one isolated shot."],
    participantLabel: "player",
    venueLabel: "court",
    actions: [
      { id: "forehand_drive", label: "Forehand drive", category: "stroke" },
      { id: "backhand_drive", label: "Backhand drive", category: "stroke" },
      { id: "forehand_volley", label: "Forehand volley", category: "stroke" },
      { id: "backhand_volley", label: "Backhand volley", category: "stroke" },
      { id: "serve", label: "Serve", category: "serve" },
      { id: "boast", label: "Boast", category: "shot" },
      { id: "drop", label: "Drop", category: "shot" },
      { id: "other", label: "Other / Not sure", category: "movement" },
    ],
    profileGoals: ["Improve swing efficiency", "Improve T-position recovery", "Improve lunging", "Improve shot accuracy"],
    rankingSystems: ["PSA", "National ranking", "Club level", "School/college", "Other"],
    biomechanics: ["racket preparation", "trunk rotation", "lunge depth", "knee alignment", "balance", "T-position recovery"],
    roleOptions: ["Singles player", "Team player", "Both"],
    playingStyleOptions: ["Attacking", "Counter-attacking", "Defensive", "All-round", "Developing"],
    enabled: false,
  },
  cricket: {
    id: "cricket",
    name: "Cricket",
    shortName: "Cricket",
    description: "Batting, bowling, fielding, movement sequencing, balance, and technical repeatability.",
    icon: "🏏",
    heroHeadline: "Understand your cricket technique frame by frame",
    heroDescription: "Analyze batting, pace or spin bowling, fielding throws, and wicketkeeping with role-specific movement and sequencing standards.",
    coachingFocus: ["Head stability and movement sequencing", "Release, impact, and follow-through efficiency"],
    filmingTips: ["For batting, film from side-on or behind the bowler's arm.", "For bowling, keep the complete run-up and follow-through in frame.", "Use a stable camera and include the crease or stumps for reference."],
    participantLabel: "athlete",
    venueLabel: "ground",
    actions: [
      { id: "front_foot_batting", label: "Front-foot batting", category: "shot" },
      { id: "back_foot_batting", label: "Back-foot batting", category: "shot" },
      { id: "defensive_shot", label: "Defensive shot", category: "shot" },
      { id: "drive", label: "Drive", category: "shot" },
      { id: "pull", label: "Pull", category: "shot" },
      { id: "bowling", label: "Bowling", category: "delivery" },
      { id: "wicketkeeping", label: "Wicketkeeping movement", category: "movement" },
      { id: "other", label: "Other / Not sure", category: "movement" },
    ],
    profileGoals: ["Improve batting timing", "Increase bowling efficiency", "Improve balance", "Improve fielding movement"],
    rankingSystems: ["ICC", "National ranking", "State/County", "Club level", "School/college", "Other"],
    biomechanics: ["head stability", "front-leg bracing", "trunk rotation", "shoulder counter-rotation", "release mechanics", "follow-through"],
    roleOptions: ["Batter", "Fast bowler", "Spin bowler", "Wicketkeeper", "All-rounder", "Fielder"],
    playingStyleOptions: ["Top-order", "Middle-order", "Finisher", "Pace", "Spin", "Wicketkeeping", "All-round"],
    enabled: false,
  },
  table_tennis: {
    id: "table_tennis",
    name: "Table Tennis",
    shortName: "Table Tennis",
    description: "Compact stroke mechanics, timing, spin generation, ready position, and recovery speed.",
    icon: "🏓",
    heroHeadline: "Improve table-tennis timing and spin with AI",
    heroDescription: "Assess compact strokes, contact timing, spin generation, footwork, and recovery using table-tennis-specific movement standards.",
    coachingFocus: ["Contact timing and racket acceleration", "Ready position, weight transfer, and recovery"],
    filmingTips: ["Keep the player, table, and racket visible.", "Film from the side or rear corner at table height.", "Use slow motion when available for serves and fast exchanges."],
    participantLabel: "player",
    venueLabel: "table",
    actions: [
      { id: "forehand_drive", label: "Forehand drive", category: "stroke" },
      { id: "backhand_drive", label: "Backhand drive", category: "stroke" },
      { id: "forehand_topspin", label: "Forehand topspin", category: "stroke" },
      { id: "backhand_topspin", label: "Backhand topspin", category: "stroke" },
      { id: "forehand_push", label: "Forehand push", category: "shot" },
      { id: "backhand_push", label: "Backhand push", category: "shot" },
      { id: "serve", label: "Serve", category: "serve" },
      { id: "smash", label: "Smash", category: "stroke" },
      { id: "other", label: "Other / Not sure", category: "movement" },
    ],
    profileGoals: ["Generate more spin", "Improve timing", "Improve footwork", "Improve serve variation"],
    rankingSystems: ["ITTF", "National rating", "USATT", "Club level", "School/college", "Other"],
    biomechanics: ["ready position", "hip rotation", "forearm acceleration", "contact timing", "weight transfer", "recovery"],
    roleOptions: ["Singles", "Doubles", "Both"],
    playingStyleOptions: ["Offensive", "Defensive", "All-round", "Chopper", "Developing"],
    enabled: false,
  },
};

export const defaultSportId: SportId = "tennis";
export const supportedSports = Object.values(sportRegistry).filter((sport) => sport.enabled);

export function getSport(sportId: string | null | undefined): SportDefinition {
  const candidate = sportRegistry[sportId as SportId];
  return candidate?.enabled ? candidate : sportRegistry[defaultSportId];
}
