import { ArrowRight, CalendarCheck2, FileVideo2, MessageCircle, PlayCircle, Target } from "lucide-react";
import Link from "next/link";

import AthleteWorkspaceShell from "@/components/layout/AthleteWorkspaceShell";
import { getSport } from "@/lib/sports";
import { getUserDashboardStats, requireUser } from "@/lib/supabase/server";

export default async function ReturningHomePage() {
  const user = await requireUser();
  const data = await getUserDashboardStats(user.id);
  const latest = data.recentSessions[0] ?? null;
  const focus = data.improvementFocus;
  const latestAnalysisAction = latest?.analysisAction ?? "pending";
  const latestStatus = latest?.status ?? "in_progress";
  const latestCreatedAt = latest?.createdAt ?? new Date().toISOString();
  const latestSportName = latest?.sportId ? getSport(latest.sportId).name : "Movement";
  return (
    <AthleteWorkspaceShell>
      <div className="mx-auto max-w-6xl">
        <header className="overflow-hidden rounded-[2rem] bg-[#1b4332] text-white shadow-2xl shadow-slate-950/15"><div className="bg-[radial-gradient(circle_at_92%_0%,rgba(121,213,255,.24),transparent_34%),radial-gradient(circle_at_0%_100%,rgba(216,255,82,.12),transparent_34%)] p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#c9a227]">Today&apos;s coaching</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.045em] sm:text-5xl">Keep moving forward.</h1><p className="mt-3 text-base leading-7 text-slate-300">One stroke, one focus, one useful next step.</p></div><Link href="/start" className="inline-flex min-h-13 items-center gap-2 rounded-xl bg-[#d7e022] px-6 font-bold text-[#1b4332] shadow-lg shadow-lime-950/10 transition hover:bg-white active:scale-[.985]">Analyze a stroke<ArrowRight className="h-4 w-4" /></Link></div><div className="mt-8 grid grid-cols-3 gap-2 border-t border-white/10 pt-5"><div><p className="text-2xl font-bold">{data.analysisCount}</p><p className="mt-1 text-xs text-slate-400">Reports</p></div><div><p className="text-2xl font-bold">{data.videoCount}</p><p className="mt-1 text-xs text-slate-400">Videos</p></div><div><p className="text-2xl font-bold">{data.averageScore ?? "—"}</p><p className="mt-1 text-xs text-slate-400">Avg score</p></div></div></div></header>
        <div className="mt-9 grid gap-5 lg:grid-cols-3">
          <section className="ath-card p-6 lg:col-span-2"><div className="flex items-center gap-2 text-sm font-semibold text-[#40916c]"><PlayCircle className="h-4 w-4" />Continue</div>{latest ? <div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">{latestSportName} · {latestAnalysisAction.replaceAll("_", " ")}</p><h2 className="mt-2 text-2xl font-semibold text-slate-950">{latest.fileName}</h2><p className="mt-2 text-sm text-slate-500">{new Date(latestCreatedAt).toLocaleDateString()} · {latestStatus.replaceAll("_", " ")}</p></div><Link href={latestStatus === "completed" ? `/report/${latest.id}` : `/analysis/${latest.id}`} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-[#d6e2cf] bg-white px-4 text-sm font-semibold text-slate-800 hover:bg-[#e6ede0]">{latestStatus === "completed" ? "Open report" : "Continue"}<ArrowRight className="h-4 w-4" /></Link></div> : <div className="mt-5 rounded-2xl border border-dashed border-[#d6e2cf] bg-[#e6ede0] p-8 text-center"><FileVideo2 className="mx-auto h-7 w-7 text-[#40916c]" /><p className="mt-3 font-semibold text-slate-950">No analysis yet</p><p className="mt-2 text-sm text-slate-600">Choose a stroke and add a short video.</p></div>}</section>
          <section className="ath-card p-6"><div className="flex items-center gap-2 text-sm font-semibold text-[#40916c]"><Target className="h-4 w-4" />Current focus</div>{focus ? <><h2 className="mt-4 text-xl font-semibold text-slate-950">{focus.primaryGoal}</h2><p className="mt-3 rounded-xl bg-[#e6ede0] p-3 text-sm font-semibold text-[#40916c]">“{focus.coachingCue}”</p><p className="mt-4 text-sm text-slate-600">{focus.completedItems}/{focus.totalItems} practice steps</p><Link href={`/report/${focus.sessionId}#practice-reassess`} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#40916c]">Practice now<ArrowRight className="h-4 w-4" /></Link></> : <p className="mt-4 text-sm leading-6 text-slate-600">Your first report will set one coaching priority.</p>}</section>
        </div>
        <div className="mt-5 grid gap-4 sm:grid-cols-3"><Link href="/practice" className="ath-card group p-5 transition hover:-translate-y-0.5 hover:border-[#52705f]"><CalendarCheck2 className="h-5 w-5 text-[#40916c]" /><p className="mt-3 font-semibold text-slate-950">Practice</p><p className="mt-1 text-sm text-slate-600">Run your active drill.</p><ArrowRight className="mt-4 h-4 w-4 text-slate-400 transition group-hover:translate-x-1 group-hover:text-[#40916c]" /></Link><Link href="/progress" className="ath-card group p-5 transition hover:-translate-y-0.5 hover:border-[#52705f]"><Target className="h-5 w-5 text-[#40916c]" /><p className="mt-3 font-semibold text-slate-950">Progress</p><p className="mt-1 text-sm text-slate-600">See how your stroke is changing.</p><ArrowRight className="mt-4 h-4 w-4 text-slate-400 transition group-hover:translate-x-1 group-hover:text-[#40916c]" /></Link>{latest?.status === "completed" ? <Link href={`/coach/${latest.id}`} className="ath-card group p-5 transition hover:-translate-y-0.5 hover:border-[#52705f]"><MessageCircle className="h-5 w-5 text-[#40916c]" /><p className="mt-3 font-semibold text-slate-950">Ask your coach</p><p className="mt-1 text-sm text-slate-600">Discuss your latest report.</p><ArrowRight className="mt-4 h-4 w-4 text-slate-400 transition group-hover:translate-x-1 group-hover:text-[#40916c]" /></Link> : <Link href="/support" className="ath-card group p-5 transition hover:-translate-y-0.5 hover:border-[#52705f]"><MessageCircle className="h-5 w-5 text-[#40916c]" /><p className="mt-3 font-semibold text-slate-950">Help</p><p className="mt-1 text-sm text-slate-600">Solve an upload or analysis issue.</p><ArrowRight className="mt-4 h-4 w-4 text-slate-400 transition group-hover:translate-x-1 group-hover:text-[#40916c]" /></Link>}</div>
      </div>
    </AthleteWorkspaceShell>
  );
}
