import { ArrowRight, CalendarCheck2, FileVideo2, MessageCircle, PlayCircle, Target } from "lucide-react";
import Link from "next/link";

import AceCoachMark from "@/components/design-system/AceCoachMark";
import { getSport } from "@/lib/sports";
import { getUserDashboardStats, requireUser } from "@/lib/supabase/server";

export default async function ReturningHomePage() {
  const user = await requireUser();
  const data = await getUserDashboardStats(user.id);
  const latest = data.recentSessions[0] ?? null;
  const focus = data.improvementFocus;
  const latestAnalysisAction = latest?.analysisAction ?? "pending";
  const latestStatus = latest?.status ?? "in_progress";
  const latestCreatedAt = latest?.createdAt ?? new Date().toISOString();
  const latestSportName = latest?.sportId ? getSport(latest.sportId).name : "Movement";
  return (
    <main className="min-h-screen bg-[#F6F8FB] text-slate-950">
      <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><AceCoachMark /><nav aria-label="Player navigation" className="flex items-center gap-1 text-sm sm:gap-2"><Link href="/start" className="hidden rounded-xl px-3 py-2 font-medium text-slate-600 hover:bg-slate-50 hover:text-slate-950 md:inline">Analyze</Link><Link href="/library" className="rounded-xl px-3 py-2 font-medium text-slate-600 hover:bg-slate-50 hover:text-slate-950">My videos</Link><Link href="/progress" className="hidden rounded-xl px-3 py-2 font-medium text-slate-600 hover:bg-slate-50 hover:text-slate-950 sm:inline">Progress</Link><Link href="/feedback" className="hidden rounded-xl px-3 py-2 font-semibold text-violet-700 hover:bg-violet-50 lg:inline">Feedback</Link><Link href="/settings" className="rounded-xl border border-slate-200 bg-white px-3 py-2 font-medium text-slate-700 shadow-sm">Account</Link></nav></div></header>
      <div className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-14">
        <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-blue-800">Your next useful action</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.035em] text-slate-950">Keep the improvement loop moving.</h1><p className="mt-3 text-base leading-7 text-slate-600">Return to your current priority, continue practice, or upload another movement.</p></div><Link href="/start" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#173F6A] px-5 font-semibold text-white hover:bg-[#103554]">Upload another video<ArrowRight className="h-4 w-4" /></Link></div>
        <div className="mt-9 grid gap-5 lg:grid-cols-3">
          <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><div className="flex items-center gap-2 text-sm font-semibold text-blue-800"><PlayCircle className="h-4 w-4" />Continue current journey</div>{latest ? <div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">{latestSportName} · {latestAnalysisAction.replaceAll("_", " ")}</p><h2 className="mt-2 text-2xl font-semibold text-slate-950">{latest.headline ?? latest.fileName}</h2><p className="mt-2 text-sm text-slate-500">{new Date(latestCreatedAt).toLocaleDateString()} · {latestStatus.replaceAll("_", " ")}</p></div><Link href={latestStatus === "completed" ? `/report/${latest.id}` : `/analysis/${latest.id}`} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-800 hover:bg-slate-50">{latestStatus === "completed" ? "Open report" : "Continue analysis"}<ArrowRight className="h-4 w-4" /></Link></div> : <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><FileVideo2 className="mx-auto h-7 w-7 text-blue-800" /><p className="mt-3 font-semibold text-slate-950">No analysis yet</p><p className="mt-2 text-sm text-slate-600">Choose a sport and upload one movement to begin.</p></div>}</section>
          <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2 text-sm font-semibold text-emerald-800"><Target className="h-4 w-4" />Active coaching priority</div>{focus ? <><h2 className="mt-4 text-xl font-semibold text-slate-950">{focus.primaryGoal}</h2><p className="mt-3 rounded-xl bg-blue-50 p-3 text-sm font-medium text-blue-950">“{focus.coachingCue}”</p><p className="mt-4 text-sm text-slate-600">Practice completed: {focus.completedItems}/{focus.totalItems}</p><Link href={`/report/${focus.sessionId}#practice-reassess`} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-blue-800">Open practice plan<ArrowRight className="h-4 w-4" /></Link></> : <p className="mt-4 text-sm leading-6 text-slate-600">Your first reliable report will create one active coaching priority.</p>}</section>
        </div>
        <div className="mt-5 grid gap-5 sm:grid-cols-3"><Link href="/practice" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-blue-300"><CalendarCheck2 className="h-5 w-5 text-emerald-700" /><p className="mt-3 font-semibold text-slate-950">Next practice</p><p className="mt-1 text-sm text-slate-600">Continue the drill connected to your active correction.</p></Link><Link href="/progress" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-blue-300"><Target className="h-5 w-5 text-blue-800" /><p className="mt-3 font-semibold text-slate-950">Progress</p><p className="mt-1 text-sm text-slate-600">Compare only compatible reassessment sessions.</p></Link>{latest?.status === "completed" ? <Link href={`/coach/${latest.id}`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-blue-300"><MessageCircle className="h-5 w-5 text-blue-800" /><p className="mt-3 font-semibold text-slate-950">Coaching conversation</p><p className="mt-1 text-sm text-slate-600">Ask questions grounded in your latest report.</p></Link> : <Link href="/support" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-blue-300"><MessageCircle className="h-5 w-5 text-blue-800" /><p className="mt-3 font-semibold text-slate-950">Support</p><p className="mt-1 text-sm text-slate-600">Get help with capture, upload, or analysis.</p></Link>}</div>
      </div>
    </main>
  );
}
